### ISSUE TITLE
kubesphere设置开机自动启动

### ISSUE THREAD

**Issue by Carriezhangyan** [kubesphere/ks-installer#102]
安装完成kubesphere后，重启服务器，发现kubesphere不能自动启动，想问一下怎样设置才能自动开机启动呢？还是该服务不能自启？

**Comment by pixiake** [comment]
这个是依赖k8s自启动的    k8s开启能够启动的   kubesphere应该就可以被自动拉起来

**Comment by Carriezhangyan** [comment]
kubesphere不是基于k8s安装的，而是直接下载离线安装包直接选择all-in-one模式安装的。kubelet.service默认安装的时候已经设置了开机启动，但是没有拉起来kubesphere。

**Comment by Carriezhangyan** [comment]
kubelet.service重新设置开机启动，重启系统就可以了。
第一次没有拉起来的原因可能是系统原因。
