### ISSUE TITLE
kubesphere登录异常

### ISSUE THREAD

**Issue by yanruogu** [kubesphere/ks-installer#1025]
安装完kubesphere 3.0版本后，出现登录异常： 

![image](https://user-images.githubusercontent.com/5188514/89802286-e9dc5e00-db63-11ea-9287-9d7effdcf2e0.png)

想卸载重装，也卸载不干净，感觉安装了不少东西去其它namespace，而并不全在kubesphere-system这个命名空间里。。

尴尬！

**Comment by yanruogu** [comment]
看到上传的图是破的，将错误贴在这里： Internal error occurred: the server could not find the requested resource (post loginrecords.iam.kubesphere.io)

**Comment by zryfish** [comment]
duplicate https://github.com/kubesphere/kubesphere/issues/2835
