### ISSUE TITLE
Multi-node安装pod ks-installer-xx-xx无法启动

### ISSUE THREAD

**Issue by liyk1024** [kubesphere/ks-installer#1033]
kubectl get pod --all-namespaces
kube-system         openebs-localpv-provisioner-77fbd6858d-4gjh8   0/1     ContainerCreating   0          160m
kube-system         openebs-ndm-7zwwc                              0/1     CrashLoopBackOff    34         160m
kube-system         openebs-ndm-operator-59c75c96fc-24lss          0/1     ContainerCreating   0          160m
kube-system         openebs-ndm-z7spr                              0/1     CrashLoopBackOff    34         160m
kube-system         tiller-deploy-79b566b5ff-4pcfb                 0/1     ContainerCreating   0          163m
kubesphere-system   ks-installer-7d9fb945c7-5nfsq                  0/1     ContainerCreating   0          160m
---
kubectl logs -n kubesphere-system ks-installer-7d9fb945c7-5nfsq 
Error from server (BadRequest): container "installer" in pod "ks-installer-7d9fb945c7-5nfsq" is waiting to start: ContainerCreating
---
kubectl -n kubesphere-system describe pod ks-installer-7d9fb945c7-5nfsq 
kubelet, node1  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "3e5504cdfe70ec48144436da29873b32844e61a0f53c4395ef1e1963892987f0" network for pod "ks-installer-7d9fb945c7-5nfsq": networkPlugin cni failed to set up pod "ks-installer-7d9fb945c7-5nfsq_kubesphere-system" network: Get https://[10.233.0.1]:443/api/v1/namespaces/kubesphere-system: net/http: TLS handshake timeout

**Comment by liyk1024** [comment]
FAILED - RETRYING: kubesphere-installer is ok (3 retries left).
FAILED - RETRYING: kubesphere-installer is ok (2 retries left).
FAILED - RETRYING: kubesphere-installer is ok (1 retries left).
fatal: [master]: FAILED! => {
    "attempts": 30, 
    "changed": true, 
    "cmd": "/usr/local/bin/kubectl get pod -n kubesphere-system | grep Running | grep ks-installer", 
    "delta": "0:00:00.126361", 
    "end": "2020-08-12 22:20:52.008495", 
    "rc": 1, 
    "start": "2020-08-12 22:20:51.882134"
}

MSG:

non-zero return code


PLAY RECAP ****************************************************************************************************************************************************************
master                     : ok=230  changed=18   unreachable=0    failed=1   
node1                      : ok=208  changed=5    unreachable=0    failed=0   
node2                      : ok=208  changed=5    unreachable=0    failed=0

**Comment by FeynmanZhou** [comment]
@liyk1024   English only.

Which version did you install? v2.1.1 or v3.0.0?

**Comment by liyk1024** [comment]
V2.1.1&nbsp;
Multi node， on-line&nbsp;installation





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubesphere/ks-installer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月16日(星期天) 中午12:41
收件人:&nbsp;"kubesphere/ks-installer"<ks-installer@noreply.github.com&gt;;
抄送:&nbsp;"liyk"<1195461076@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [kubesphere/ks-installer] Multi-node安装pod ks-installer-xx-xx无法启动 (#1033)





 
@liyk1024   English only.
 
Which version did you install? v2.1.1 or v3.0.0?

**Comment by FeynmanZhou** [comment]
@pixiake Please help to take a look at this issue.
