### ISSUE TITLE
Custom project role isn't migrated after upgrading from 2.1.x to 3.0.0

### ISSUE THREAD

**Issue by benjaminhuo** [kubesphere/ks-installer#1073]
- Create a custom project manage role with project management capability under a project in 2.1.x
- Create a project account of this custom project role
- Upgrade to 3.0.0
- The custom project role in 3.0.0 hasn't any project management capability

![image](https://user-images.githubusercontent.com/18525465/90958717-c3ee7c00-e4c8-11ea-83ca-d83b679462a8.png)

![image](https://user-images.githubusercontent.com/18525465/90958713-b933e700-e4c8-11ea-8c49-6da308be9d9c.png)

![Snip20200822_40](https://user-images.githubusercontent.com/18525465/90958736-dec0f080-e4c8-11ea-8a85-54515974f90e.png)

2.1.1
![Snip20200822_36](https://user-images.githubusercontent.com/18525465/90958748-eed8d000-e4c8-11ea-981d-0835259c38a1.png)

3.0.0
![Snip20200822_45](https://user-images.githubusercontent.com/18525465/90958762-0e6ff880-e4c9-11ea-80fd-b71c05e0d1f7.png)

**Comment by benjaminhuo** [comment]
> @huanggze pls help to verify this issue .

guangzhe is busy on upgrading fluentbit operator, @wanjunlei would you help to verify this issue?
I reproduced it twice last Friday, and then hongming fixed it

**Comment by wanjunlei** [comment]
ok

**Comment by wanjunlei** [comment]
This bug still exists.
@wansir

**Comment by wanjunlei** [comment]
verified
/close

**Comment by benjaminhuo** [comment]
Thanks @wanjunlei 
/close
