### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by zhenglianbin** [kubesphere/ks-installer#1109]
![image](https://user-images.githubusercontent.com/61683462/92222041-fa68c580-eed0-11ea-9cc5-5c936a4e355c.png)

**Comment by zryfish** [comment]
Can you check log of ks-apiserver and ks-controller-manager by using following command ?
```
kubectl -n kubesphere-system logs ks-apiserver-xxxxxxxxx
kubectl -n kubesphere-system logs ks-controller-manager-xxxxxxxxx
```

**Comment by zhenglianbin** [comment]
The logs for  ks-apiserver

2020/09/07 10:44:16 http: panic serving 10.193.16.58:27428: runtime error: invalid memory address or nil pointer dereference
goroutine 1037453 [running]:
net/http.(*conn).serve.func1(0xc0004b94a0)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:1795 +0x139
panic(0x2d36da0, 0x5450320)
	/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/panic.go:679 +0x1b2
kubesphere.io/kubesphere/pkg/models/resources/v1alpha2/storageclass.(*storageClassesSearcher).countPersistentVolumeClaims(0xc00030f4e0, 0xc001510840, 0x13, 0x54c6d68)
	/home/runner/work/kubesphere/kubesphere/pkg/models/resources/v1alpha2/storageclass/storageclasses.go:110 +0x12c
kubesphere.io/kubesphere/pkg/models/resources/v1alpha2/storageclass.(*storageClassesSearcher).Search(0xc00030f4e0, 0x0, 0x0, 0xc001546260, 0xc00339a7c2, 0xa, 0x1, 0x2e5db20, 0xc002254c00, 0x0, ...)
	/home/runner/work/kubesphere/kubesphere/pkg/models/resources/v1alpha2/storageclass/storageclasses.go:92 +0x2f0
kubesphere.io/kubesphere/pkg/models/resources/v1alpha2/resource.(*ResourceGetter).ListResources(0xc0009a20f8, 0x0, 0x0, 0xc00339a7ac, 0xe, 0xc001546260, 0xc00339a7c2, 0xa, 0x299a801, 0xa, ...)
	/home/runner/work/kubesphere/kubesphere/pkg/models/resources/v1alpha2/resource/resources.go:123 +0x23e
kubesphere.io/kubesphere/pkg/kapis/resources/v1alpha3.(*Handler).fallback(0xc00030f500, 0xc00339a7ac, 0xe, 0x0, 0x0, 0xc002f40bc0, 0x0, 0x3856240, 0xc0004d1560)
	/home/runner/work/kubesphere/kubesphere/pkg/kapis/resources/v1alpha3/handler.go:155 +0xb0b
kubesphere.io/kubesphere/pkg/kapis/resources/v1alpha3.(*Handler).handleListResources(0xc00030f500, 0xc0022549f0, 0xc00032a7e0)
	/home/runner/work/kubesphere/kubesphere/pkg/kapis/resources/v1alpha3/handler.go:97 +0x2cb
github.com/emicklei/go-restful.(*Container).dispatch.func5(0xc0022549f0, 0xc00032a7e0)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/container.go:283 +0x3e
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc002254a80, 0xc0022549f0, 0xc00032a7e0)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/filter.go:21 +0x8b
kubesphere.io/kubesphere/pkg/apiserver.logRequestAndResponse(0xc0022549f0, 0xc00032a7e0, 0xc002254a80)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/apiserver.go:531 +0x82
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc002254a80, 0xc0022549f0, 0xc00032a7e0)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/filter.go:19 +0x65
github.com/emicklei/go-restful.(*Container).dispatch(0xc000715cb0, 0x38c1500, 0xc002254990, 0xc000d83100)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/container.go:285 +0x866
net/http.HandlerFunc.ServeHTTP(0xc0003c6c80, 0x38c1500, 0xc002254990, 0xc000d83100)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0001d4540, 0x38c1500, 0xc002254990, 0xc000d83100)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2416 +0x1bd
github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc000715cb0, 0x38c1500, 0xc002254990, 0xc000d83100)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/container.go:303 +0x4d
kubesphere.io/kubesphere/pkg/apiserver/filters.WithKubeAPIServer.func1(0x38c1500, 0xc002254990, 0xc000d83100)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/kubeapiserver.go:71 +0x37f
net/http.HandlerFunc.ServeHTTP(0xc000484280, 0x38c1500, 0xc002254990, 0xc000d83100)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuditing.func1(0x38c1b80, 0xc000b52e00, 0xc000d83100)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/auditing.go:54 +0x1b8
net/http.HandlerFunc.ServeHTTP(0xc00094dce0, 0x38c1b80, 0xc000b52e00, 0xc000d83100)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuthorization.func1(0x38c1b80, 0xc000b52e00, 0xc000d83100)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/authorization.go:50 +0x37c
net/http.HandlerFunc.ServeHTTP(0xc0004843c0, 0x38c1b80, 0xc000b52e00, 0xc000d83100)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuthentication.func1(0x38c1b80, 0xc000b52e00, 0xc000d83000)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/authentication.go:95 +0xb6b
net/http.HandlerFunc.ServeHTTP(0xc0000db090, 0x38c1b80, 0xc000b52e00, 0xc000d83000)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithRequestInfo.func1(0x38c1b80, 0xc000b52e00, 0xc000d82f00)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/requestinfo.go:67 +0x3c5
net/http.HandlerFunc.ServeHTTP(0xc0009bebd0, 0x38c1b80, 0xc000b52e00, 0xc000d82f00)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
net/http.serverHandler.ServeHTTP(0xc00022c1c0, 0x38c1b80, 0xc000b52e00, 0xc000d82f00)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2831 +0xa4
net/http.(*conn).serve(0xc0004b94a0, 0x38d4780, 0xc0009b3b00)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:1919 +0x875
created by net/http.(*Server).Serve
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2957 +0x384
2020/09/07 10:45:09 http: panic serving 10.193.16.58:17482: runtime error: invalid memory address or nil pointer dereference
goroutine 1037704 [running]:
net/http.(*conn).serve.func1(0xc00099eaa0)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:1795 +0x139
panic(0x2d36da0, 0x5450320)
	/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/panic.go:679 +0x1b2
kubesphere.io/kubesphere/pkg/models/resources/v1alpha2/storageclass.(*storageClassesSearcher).countPersistentVolumeClaims(0xc00030f4e0, 0xc001510840, 0x13, 0x54c6d68)
	/home/runner/work/kubesphere/kubesphere/pkg/models/resources/v1alpha2/storageclass/storageclasses.go:110 +0x12c
kubesphere.io/kubesphere/pkg/models/resources/v1alpha2/storageclass.(*storageClassesSearcher).Search(0xc00030f4e0, 0x0, 0x0, 0xc0004d1380, 0xc003045c62, 0xa, 0x1, 0x2e5db20, 0xc002ade840, 0x0, ...)
	/home/runner/work/kubesphere/kubesphere/pkg/models/resources/v1alpha2/storageclass/storageclasses.go:92 +0x2f0
kubesphere.io/kubesphere/pkg/models/resources/v1alpha2/resource.(*ResourceGetter).ListResources(0xc0009a20f8, 0x0, 0x0, 0xc003045c4c, 0xe, 0xc0004d1380, 0xc003045c62, 0xa, 0x299a801, 0xa, ...)
	/home/runner/work/kubesphere/kubesphere/pkg/models/resources/v1alpha2/resource/resources.go:123 +0x23e
kubesphere.io/kubesphere/pkg/kapis/resources/v1alpha3.(*Handler).fallback(0xc00030f500, 0xc003045c4c, 0xe, 0x0, 0x0, 0xc002ab2600, 0x0, 0x3856240, 0xc0004d1560)
	/home/runner/work/kubesphere/kubesphere/pkg/kapis/resources/v1alpha3/handler.go:155 +0xb0b
kubesphere.io/kubesphere/pkg/kapis/resources/v1alpha3.(*Handler).handleListResources(0xc00030f500, 0xc002ade630, 0xc000346d20)
	/home/runner/work/kubesphere/kubesphere/pkg/kapis/resources/v1alpha3/handler.go:97 +0x2cb
github.com/emicklei/go-restful.(*Container).dispatch.func5(0xc002ade630, 0xc000346d20)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/container.go:283 +0x3e
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc002ade6c0, 0xc002ade630, 0xc000346d20)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/filter.go:21 +0x8b
kubesphere.io/kubesphere/pkg/apiserver.logRequestAndResponse(0xc002ade630, 0xc000346d20, 0xc002ade6c0)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/apiserver.go:531 +0x82
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc002ade6c0, 0xc002ade630, 0xc000346d20)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/filter.go:19 +0x65
github.com/emicklei/go-restful.(*Container).dispatch(0xc000715cb0, 0x38c1500, 0xc002ade5d0, 0xc0038f2200)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/container.go:285 +0x866
net/http.HandlerFunc.ServeHTTP(0xc0003c6c80, 0x38c1500, 0xc002ade5d0, 0xc0038f2200)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0001d4540, 0x38c1500, 0xc002ade5d0, 0xc0038f2200)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2416 +0x1bd
github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc000715cb0, 0x38c1500, 0xc002ade5d0, 0xc0038f2200)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/container.go:303 +0x4d
kubesphere.io/kubesphere/pkg/apiserver/filters.WithKubeAPIServer.func1(0x38c1500, 0xc002ade5d0, 0xc0038f2200)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/kubeapiserver.go:71 +0x37f
net/http.HandlerFunc.ServeHTTP(0xc000484280, 0x38c1500, 0xc002ade5d0, 0xc0038f2200)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuditing.func1(0x38c1b80, 0xc0026480e0, 0xc0038f2200)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/auditing.go:54 +0x1b8
net/http.HandlerFunc.ServeHTTP(0xc00094dce0, 0x38c1b80, 0xc0026480e0, 0xc0038f2200)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuthorization.func1(0x38c1b80, 0xc0026480e0, 0xc0038f2200)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/authorization.go:50 +0x37c
net/http.HandlerFunc.ServeHTTP(0xc0004843c0, 0x38c1b80, 0xc0026480e0, 0xc0038f2200)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuthentication.func1(0x38c1b80, 0xc0026480e0, 0xc003196300)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/authentication.go:95 +0xb6b
net/http.HandlerFunc.ServeHTTP(0xc0000db090, 0x38c1b80, 0xc0026480e0, 0xc003196300)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithRequestInfo.func1(0x38c1b80, 0xc0026480e0, 0xc003196200)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/requestinfo.go:67 +0x3c5
net/http.HandlerFunc.ServeHTTP(0xc0009bebd0, 0x38c1b80, 0xc0026480e0, 0xc003196200)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
net/http.serverHandler.ServeHTTP(0xc00022c1c0, 0x38c1b80, 0xc0026480e0, 0xc003196200)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2831 +0xa4
net/http.(*conn).serve(0xc00099eaa0, 0x38d4780, 0xc0039cd140)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:1919 +0x875
created by net/http.(*Server).Serve
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2957 +0x384

**Comment by zhenglianbin** [comment]
The logs  for ks-controller-manager 

I0907 10:40:07.721328       1 workspacerole.go:205] Successfully synced key:sewc-self-provisioner
I0907 10:40:07.721386       1 event.go:281] Event(v1.ObjectReference{Kind:"WorkspaceRole", Namespace:"", Name:"sewc-self-provisioner", UID:"9e7a4e73-b047-4812-9b95-b375a581a330", APIVersion:"iam.kubesphere.io/v1alpha2", ResourceVersion:"3713342", FieldPath:""}): type: 'Normal' reason: 'Synced' WorkspaceRole synced successfully
I0907 10:40:07.721437       1 workspacerole.go:205] Successfully synced key:sewc-self-provisioner
I0907 10:40:07.721516       1 event.go:281] Event(v1.ObjectReference{Kind:"WorkspaceRole", Namespace:"", Name:"sewc-self-provisioner", UID:"9e7a4e73-b047-4812-9b95-b375a581a330", APIVersion:"iam.kubesphere.io/v1alpha2", ResourceVersion:"3713343", FieldPath:""}): type: 'Normal' reason: 'Synced' WorkspaceRole synced successfully
I0907 10:40:07.744767       1 workspacerole.go:205] Successfully synced key:sewc-viewer
I0907 10:40:07.744865       1 workspacerole.go:205] Successfully synced key:sewc-viewer
I0907 10:40:07.744914       1 event.go:281] Event(v1.ObjectReference{Kind:"WorkspaceRole", Namespace:"", Name:"sewc-viewer", UID:"e232b078-aefe-486e-85c7-ef28e3a1ee60", APIVersion:"iam.kubesphere.io/v1alpha2", ResourceVersion:"3713348", FieldPath:""}): type: 'Normal' reason: 'Synced' WorkspaceRole synced successfully
I0907 10:40:07.744960       1 event.go:281] Event(v1.ObjectReference{Kind:"WorkspaceRole", Namespace:"", Name:"sewc-viewer", UID:"e232b078-aefe-486e-85c7-ef28e3a1ee60", APIVersion:"iam.kubesphere.io/v1alpha2", ResourceVersion:"3713346", FieldPath:""}): type: 'Normal' reason: 'Synced' WorkspaceRole synced successfully
I0907 10:40:07.754676       1 workspacerole.go:205] Successfully synced key:sewc-regular
I0907 10:40:07.754738       1 event.go:281] Event(v1.ObjectReference{Kind:"WorkspaceRole", Namespace:"", Name:"sewc-regular", UID:"1ed57841-6472-4dfb-8548-1356c80d7c0a", APIVersion:"iam.kubesphere.io/v1alpha2", ResourceVersion:"3713349", FieldPath:""}): type: 'Normal' reason: 'Synced' WorkspaceRole synced successfully
I0907 10:40:07.756400       1 workspacerole.go:205] Successfully synced key:sewc-regular
I0907 10:40:07.756487       1 event.go:281] Event(v1.ObjectReference{Kind:"WorkspaceRole", Namespace:"", Name:"sewc-regular", UID:"1ed57841-6472-4dfb-8548-1356c80d7c0a", APIVersion:"iam.kubesphere.io/v1alpha2", ResourceVersion:"3713351", FieldPath:""}): type: 'Normal' reason: 'Synced' WorkspaceRole synced successfully
I0907 10:40:07.762752       1 workspacetemplate_controller.go:200] Successfully synced key:sewc
I0907 10:40:07.762880       1 event.go:281] Event(v1.ObjectReference{Kind:"WorkspaceTemplate", Namespace:"", Name:"sewc", UID:"ccdebc0f-44da-44d8-96bf-6a188f00b526", APIVersion:"tenant.kubesphere.io/v1alpha2", ResourceVersion:"3713338", FieldPath:""}): type: 'Normal' reason: 'Synced' WorkspaceTemplate synced successfully
I0907 10:40:07.776526       1 workspacerolebinding_controller.go:205] Successfully synced key:admin-sewc-admin
I0907 10:40:07.776613       1 event.go:281] Event(v1.ObjectReference{Kind:"WorkspaceRoleBinding", Namespace:"", Name:"admin-sewc-admin", UID:"b30f2e81-1d8c-4187-ace1-21c2245abc49", APIVersion:"iam.kubesphere.io/v1alpha2", ResourceVersion:"3713353", FieldPath:""}): type: 'Normal' reason: 'Synced' WorkspaceRoleBinding synced successfully
I0907 10:40:07.777000       1 workspacerolebinding_controller.go:205] Successfully synced key:admin-sewc-admin
I0907 10:40:07.777048       1 event.go:281] Event(v1.ObjectReference{Kind:"WorkspaceRoleBinding", Namespace:"", Name:"admin-sewc-admin", UID:"b30f2e81-1d8c-4187-ace1-21c2245abc49", APIVersion:"iam.kubesphere.io/v1alpha2", ResourceVersion:"3713356", FieldPath:""}): type: 'Normal' reason: 'Synced' WorkspaceRoleBinding synced successfully
I0907 10:45:07.147231       1 ns_k8s.go:256] Found 0 policies in k8s datastore:

**Comment by min-zh** [comment]
@zhenglianbin  Could you  show all pvc information by "kubectl get pvc -A -o yaml ", let me know what pvc you have in you cluster?

**Comment by technologynongmin** [comment]
I also encountered the same problem， how to solved

**Comment by stoneshi-yunify** [comment]
The root cause of this issue is one or more PVCs don't have a storage class name, thus cause the below check panic.

`pkg/models/resources/v1alpha2/storageclass/storageclasses.go` line 110:
```go
if *pvc.Spec.StorageClassName == name
```

I believe the front-end(kubesphere web console -> storage -> storage classes) already prevents empty storage class name creation, so how this issue can happen? Where is the problematic storage class from?  @min-zh

**Comment by th3n3xtg3n3ration** [comment]
I solved this issue by adding `StorageClassName` in pvc yaml which doesn't have `StorageClassName` line such as:
```
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-pvc-12
  annotations:
    volume.beta.kubernetes.io/storage-class: thin-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: thin-disk

```
Edit pvc yaml:
![image](https://user-images.githubusercontent.com/27870123/93046685-215a9080-f663-11ea-9e8b-ba371cf02534.png)

It was fixed after I added storageClassName line to pvc yaml:
![image](https://user-images.githubusercontent.com/27870123/93046785-641c6880-f663-11ea-9dcf-5d36c596bd26.png)

**Comment by technologynongmin** [comment]
@th3n3xtg3n3ration  how to configure it?

**Comment by th3n3xtg3n3ration** [comment]
@technologynongmin 

From Volumes section, we can see that there is no storageClassName line in one of my Persistent Volume Claims such as:

![image](https://user-images.githubusercontent.com/27870123/93428116-94fcd780-f8c7-11ea-823f-38b2d0902a3d.png)

Let's look at my Storage Classes as follows:

![image](https://user-images.githubusercontent.com/27870123/93428354-f15ff700-f8c7-11ea-9b64-8fb322e677cc.png)

There is internal error in Storage Classes now as we can see such as:

![image](https://user-images.githubusercontent.com/27870123/93428843-d5a92080-f8c8-11ea-8c14-66490d031a9d.png)

Let's fix this issue by turning back to Volumes section again and edit yaml of pvc without storageClassName:

![image](https://user-images.githubusercontent.com/27870123/93429418-ca0a2980-f8c9-11ea-9a57-73a22a80525a.png)

As we can see that there is no storageClassName line in this yaml such as:

![image](https://user-images.githubusercontent.com/27870123/93429563-076eb700-f8ca-11ea-96ab-41fb8322fd17.png)

Let's add storageClassName line to the yaml and update it:

![image](https://user-images.githubusercontent.com/27870123/93430002-aa273580-f8ca-11ea-9bc7-5949c046b094.png)

Now, we can see that our storageClass Name was added here:

![image](https://user-images.githubusercontent.com/27870123/93430213-fc685680-f8ca-11ea-8ef6-7f2a713dbcc0.png)

Let's take a look at our Storage Classes section:

![image](https://user-images.githubusercontent.com/27870123/93430441-59fca300-f8cb-11ea-9a5c-a3f471d287ff.png)

Woow, there is no internal error now. So, we fixed it.

**Comment by technologynongmin** [comment]
@th3n3xtg3n3ration  
thanks your help ,
it‘s my pvc yaml, my storageclass is local-path-provisioner, maybe  not support
![image](https://user-images.githubusercontent.com/42291467/93456672-99011780-f910-11ea-90e7-33e5cf919691.png)
