### ISSUE TITLE
Lost custom configuration

### ISSUE THREAD

**Issue by wansir** [kubesphere/ks-installer#1113]
The configuration of kubesphere-config is overwritten after restarting ks-installer.

**Comment by wansir** [comment]
fix: https://github.com/kubesphere/ks-installer/pull/1376

/close

**Comment by llmgo** [comment]
I still have this problem
kubesphere 3.1.0

**Comment by hurricane1988** [comment]
I hava the problem with OICD
kubesphere 3.1.1
