### ISSUE TITLE
Join to cluster if needed

### ISSUE THREAD

**Issue by dbyanhome** [kubesphere/ks-installer#116]
安装集群版本的时候出现这个问题

**Comment by Forest-L** [comment]
报错信息麻烦截全，方便排查问题。

**Comment by Wandering** [comment]
我也遇到了这个问题
一直卡在这里
![image](https://user-images.githubusercontent.com/11769582/67472306-7b391d00-f683-11e9-9dee-e5acce145d7c.png)

![image](https://user-images.githubusercontent.com/11769582/67472262-6d839780-f683-11e9-9d72-5bac1c07ced8.png)
