### ISSUE TITLE
k8s上最小化安装KubeSphere之后，安装应用商店openpirtix，容器始终处于初始化 

### ISSUE THREAD

**Issue by ladyishenlong** [kubesphere/ks-installer#1160]
最小化安装KubeSphere之后，按照官网方法安装了了devops正常，然后安装应用商店时候安装mysql和etcd一直在初始化中

**Comment by ladyishenlong** [comment]
我删除重新安装了kubsphere之后mysql的状态转为正常，但是etcd还是在容器创建中

**Comment by pixiake** [comment]
You can check to see if etcd‘s pvc had been created.

You can post a question or search for a solution in the forum.
https://kubesphere.com.cn/forum
