### ISSUE TITLE
jenkins :User admin not found in directory

### ISSUE THREAD

**Issue by MRGUO840140** [kubesphere/ks-installer#1188]
I just installed the Jenkins plug-in, and the service didn't show any errors. But when I entered the pipeline page, an error occurred. Query Jenkins log: org.acegisecurity.userdetails .UsernameNotFoundException: User admin not found in directory.
![image](https://user-images.githubusercontent.com/62984381/101147762-c16af900-3657-11eb-8258-ac1f9ea37513.png)
![image](https://user-images.githubusercontent.com/62984381/101147614-95e80e80-3657-11eb-9b74-b80cf9c2f6e2.png)
![image](https://user-images.githubusercontent.com/62984381/101147639-9e404980-3657-11eb-900e-016405563c06.png)

**Comment by wansir** [comment]
duplicated: https://github.com/kubesphere/kubesphere/issues/3105

Which version are you using, this issue may be due to the incorrectly ks-installer version.
``` 
kubectl -n kubesphere-system get deploy ks-installer -o jsonpath='{.spec.template.spec.containers[0].image}'
```

You can fix it after changing your password by the following command.
```
kubectl patch users admin -p '{"spec":{"password":"<your password>"}}' --type='merge' && kubectl annotate users admin iam.kubesphere.io/password-encrypted-
```

**Comment by MRGUO840140** [comment]
Thanks, using your command has been resolved

**Comment by LinuxSuRen** [comment]
/kind support

hi @MRGUO840140 , thanks for reaching out to us. It looks like you already resolved your problems. I guess we can close this issue. Right?
