### ISSUE TITLE
Upgrade nginx ingress controller version

### ISSUE THREAD

**Issue by wenhuwang** [kubesphere/ks-installer#1252]
The Latest release version of nginx-ingress-controller is already v0.44.0, it is a recommended to upgrade the latest release version.

/assign @wenhuwang

**Comment by zackzhangkai** [comment]
0.44 is the latest version. Why do you want to upgrade it officially? Otherwise, you can upgrade it by yourself to meet your special requirement.

**Comment by LinuxSuRen** [comment]
Using the latest version might be or not a good solution. No matter what, please list the reasons that you think it's worth upgrading it.

**Comment by wenhuwang** [comment]
We have encountered some bugs in the configuration of https certificate in the process of using nginx-ingress. The later version of nginx-ingress has been fixed. There may be many similar bugs, so I suggest to upgrade the version appropriately. We can discuss the specific version.
