### ISSUE TITLE
s2ibuildertemplates was loaded incorrectly by recent ks-installer

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/ks-installer#1429]
# Description

s2ibuildertemplates was loaded incorrectly by recent ks-installer.

# Reproduce

Recently, I installed kubesphere with [kubekey](https://github.com/kubesphere/kubekey/releases/tag/v1.1.0-alpha.2) with the following steps:

- Download kubeky and decompress it

  ```bash
  wget -c https://github.com/kubesphere/kubekey/releases/download/v1.1.0-alpha.2/kubekey-v1.1.0-alpha.2-linux-amd64.tar.gz
  tar xzvf kubekey-v1.1.0-alpha.2-linux-amd64.tar.gz
  ```

- Up kubernetes and kubesphere

  ```bash
  ./kk create cluster --with-kubesphere nightly-20210418
  ```

- Enable DevOps component

  ```bash
  kubectl -nkubesphere-system edit cc ks-installer
  ```

  Turn `spec.devops.enabled` into `true`.

  > More powerful tool to enable ks component if you are interested: <https://github.com/LinuxSuRen/ks>

- Waiting for kubesphere up

  or use the below command to check up status:

  ```bash
  kubectl logs -n kubesphere-system $(kubectl get pod -n kubesphere-system -l app=ks-install -o jsonpath='{.items[0].metadata.name}') -f
  ```

# Check

Now we can check if s2ibuildertemplates were loaded correctly.

```bash
kubectl get s2ibuildertemplates.devops.kubesphere.io -A
```

You would find that the si2buildertemplates were missing.

- Result

  ```bash
  No resources found
  ```

- Expected

  ```bash
  NAME     FRAMEWORK   DEFAULTBASEIMAGE                           VERSION
  binary   binary      kubesphere/s2i-binary:v2.1.0               0.0.1
  java     java        kubesphere/java-8-centos7:v2.1.0           0.0.1
  nodejs   nodejs      kubesphere/nodejs-8-centos7:v2.1.0         0.0.1
  python   python      kubesphere/python-36-centos7:v2.1.0        0.0.1
  tomcat   java        kubesphere/tomcat85-java8-centos7:v2.1.0   0.0.1
  ```

# Influence

![image](https://user-images.githubusercontent.com/16865714/115331416-6b42c080-a1c8-11eb-82bc-3f65e189fe7c.png)

By the way, kubesphere 3.0.0 has no problem.

**Comment by zryfish** [comment]
Found the cause, working on it. 
/assign

**Comment by JohnNiang** [comment]
@zryfish The latest ks-installer(nightly-20210423) didn't fix this issue yet. #1441 might not be a solution for this problem.
