### ISSUE TITLE
fluent希望可以filter日志类型，默认是收集所有容器日志

### ISSUE THREAD

**Issue by kerven88** [kubesphere/ks-installer#15]
目前的版本不支持过滤需要收集的日志类型，默认收集了所有容器日志，业务量日志比较大的话，es集群扛不住，queue容易堵死，fluent发给es返回错误码429。

**Comment by benjaminhuo** [comment]
现在 fluentbit 也支持通过 ui 上改配置文件设置 filter，我们以后会把这个filter设置 设计的更友好。
现在具体怎么配置稍后我们会整理出一个文档
