### ISSUE TITLE
How to bring my own prometheus

### ISSUE THREAD

**Issue by yangchuansheng** [kubesphere/ks-installer#1503]
If prometheus already exist before installing KubeSphere，how to use my own Prometheus stack setup in KubeSphere？and I don't want to install customized Prometheus stack of KubeSphere either.

**Comment by zhu733756** [comment]
Refer to https://kubesphere.io/docs/faq/observability/byop/

**Comment by yangchuansheng** [comment]
> Refer to [kubesphere.io/docs/faq/observability/byop](https://kubesphere.io/docs/faq/observability/byop/)

but I don't want to install customized Prometheus stack of KubeSphere, this article can not help me.

**Comment by zhu733756** [comment]
Ok, I misunderstanded about it. I just see the title.

**Comment by zhu733756** [comment]
@yangchuansheng Hi, I pull a request and try to fix this issue. Once you use your own prometheus stack,  it is recommended to install kubeSphere customized stuff as mentioned at  [here](https://kubesphere.io/docs/faq/observability/byop/#step-3-install-kubesphere-customized-stuff-to-your-prometheus-stack). Some metrics rely on these configurations.

**Comment by KR411-prog** [comment]
Have you been successfull in bringing your own Prometheus,Alertmanager and Grafana when the cluster already has Kubesphere? If yes, please share some details on this. https://kubesphere.io/docs/faq/observability/byop/#step-3-install-kubesphere-customized-stuff-to-your-prometheus-stack didnt help much
