### ISSUE TITLE
青云和阿里云不同环境的机器，pip包冲突

### ISSUE THREAD

**Issue by Forest-L** [kubesphere/ks-installer#16]
![image](https://user-images.githubusercontent.com/50984129/63170113-24074280-c06b-11e9-80d4-0e271ad16e0d.png)

执行离线安装脚本报如图显示的错误：pip安装ansible报错

**Comment by lilinlinlin** [comment]
临时解决方法：
方法1
pip install setuptools==33.1.1
方法2 
下载新版setuptools
```
wget https://files.pythonhosted.org/packages/e5/53/92a8ac9d252ec170d9197dcf988f07e02305a06078d7e83a41ba4e3ed65b/setuptools-33.1.1-py2.py3-none-any.whl

pip install setuptools-33.1.1-py2.py3-none-any.whl
```
