### ISSUE TITLE
Invalid nightly build

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/ks-installer#1646]
### Background

Recently, I installed a KubeSphere with version `nightly-20210817`, and I found that the version of `ks-apiserver`, `ks-controller-manager` and `ks-console` was `v3.1.1-rc.1`, not `nightly-20210817`.

### Investigation

Please see the codes below:

https://github.com/kubesphere/ks-installer/blob/4e5175bd4523f97e03544cba553dddd5c1aa0ca1/.github/workflows/nightly-builds.yml#L25-L27

https://github.com/kubesphere/ks-installer/blob/4e5175bd4523f97e03544cba553dddd5c1aa0ca1/roles/download/defaults/main.yml#L61-L66

There no such variable `ks_image_tag`, so variable `ks-version` should be changed here.

/kind bug

**Comment by JohnNiang** [comment]
Not only in nightly build, e2e test may also have the same problem here.

**Comment by JohnNiang** [comment]
hi @pixiake , how is it going now : P

**Comment by pixiake** [comment]
Done

**Comment by JohnNiang** [comment]
Hi @pixiake , I found that the docker image `kubespheredev/ks-installer:master` had a same problem. It would be better if it could be repaired.

**Comment by JohnNiang** [comment]
> Hi @pixiake , I found that the docker image `kubespheredev/ks-installer:master` had a same problem. It would be better if it could be repaired.

I confirmed that the issue had been fixed by:

https://github.com/kubesphere/ks-installer/blob/b3e3982ab75d3ca131b18b45a61c40df5de82cdf/roles/download/defaults/main.yml#L61-L66
