### ISSUE TITLE
ubuntu上安装失败 | 不能找到pip

### ISSUE THREAD

**Issue by junotx** [kubesphere/ks-installer#166]
![image](https://user-images.githubusercontent.com/49136171/65830208-fc4d0080-e2df-11e9-97fb-522886ca912b.png)

**Comment by mayuhope** [comment]
ubuntu  18.04上安装存在同样的问题：
![image](https://user-images.githubusercontent.com/7677050/66620987-14dce500-ec15-11e9-9cd9-d0fa39b5ee09.png)
