### ISSUE TITLE
Devops upgrade failed

### ISSUE THREAD

**Issue by pixiake** [kubesphere/ks-installer#1697]
KkubeSphere Version:  v3.2.0-alpha.0

Description:
```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: Secret \"s2i-webhook-server-cert\" in namespace \"kubesphere-devops-system\" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key \"app.kubernetes.io/managed-by\": must be set to \"Helm\"; annotation validation error: missing key \"meta.helm.sh/release-name\": must be set to \"devops\"; annotation validation error: missing key \"meta.helm.sh/release-namespace\": must be set to \"kubesphere-devops-system\"    
```

When devops was upgraded, resources already existed, but they lacked Helm's annotations and labels.

I think the the solution of ks-core can be refered.
https://github.com/kubesphere/ks-installer/blob/d6eaacc83992c40676e2de5ce0ef11343f92ad38/roles/ks-core/ks-core/tasks/main.yaml#L47

**Comment by JohnNiang** [comment]
Thanks for reporting this issue. Please follow up on this issue: https://github.com/kubesphere-sigs/ks-devops-helm-chart/issues/3
