### ISSUE TITLE
Fail to install with qingcloud csi

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/ks-installer#179]
Install with multiple nodes, and see below logs in kube-cloudl-controller-manager pod: 
_I1004 14:25:30.562745       1 event.go:258] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kubesphere-monitoring-system", Name:"prometheus-k8s-system-db-prometheus-k8s-system-1", UID:"a95d8599-393c-4c32-8f24-62c741c92305", APIVersion:"v1", ResourceVersion:"11481", FieldPath:""}): type: 'Normal' reason: 'FailedBinding' no persistent volumes available for this claim and no storage class is set_

**My vars.yml set storage class as below:**
defaultStorage: "csi-qingcloud"   # "csi-qingcloud"

# QingCloud CSI 
qingcloud_csi_enabled: true
qingcloud_csi_is_default_class: true
#The type of volume in QingCloud IaaS platform. 
# 0 represents high performance volume
# 3 respresents super high performance volume.
# 1 or 2 represents high capacity volume depending on cluste's zone
# 5 represents enterprise distributed SAN (NeonSAN) volume
# 100 represents basic volume
# 200 represents SSD enterprise volume.
qingcloud_type: 100
qingcloud_maxSize: 5000
qingcloud_minSize: 100
qingcloud_stepSize: 50
qingcloud_fsType: ext4
# 1 means single replica, 2 means multiple replicas. Default 2.
qingcloud_disk_replica: 2

**Comment by pixiake** [comment]
#186
