### ISSUE TITLE
Installer not works for   eks for k8s v1.20 in china, pod ks-console  not exist

### ISSUE THREAD

**Issue by DevOpserzhao** [kubesphere/ks-installer#1795]
kubectl apply -f https://github.com/kubesphere/ks-installer/releases/download/v3.2.0/kubesphere-installer.yaml

kubectl apply -f https://github.com/kubesphere/ks-installer/releases/download/v3.2.0/cluster-configuration.yaml

Start installing monitoring
Start installing multicluster
Start installing openpitrix
Start installing network
**************************************************
Waiting for all tasks to be completed ...
task multicluster status is successful  (1/4)
task network status is successful  (2/4)
task openpitrix status is successful  (3/4)
task monitoring status is successful  (4/4)
**************************************************
Collecting installation results ...
Failed to ansible-playbook result-info.yaml

**Comment by peter4431** [comment]
same issue with k8s 1.20.6
PLAY RECAP *********************************************************************
localhost                  : ok=26   changed=19   unreachable=0    failed=0    skipped=13   rescued=0    ignored=0

Start installing monitoring
Start installing multicluster
Start installing openpitrix
Start installing network
**************************************************
Waiting for all tasks to be completed ...
task multicluster status is successful  (1/4)
task openpitrix status is successful  (2/4)
task network status is successful  (3/4)
task monitoring status is successful  (4/4)
**************************************************
Collecting installation results ...
Failed to ansible-playbook result-info.yaml

**Comment by pixiake** [comment]
please execute the following command to check:
```
helm list -n kubesphere-system
kubectl get deploy,rs -n kubesphere-system 
```

**Comment by watsy0007** [comment]
the same issue in aws eks 1.21

```shell
helm list -n kubesphere-system
```
result

```
NAME   	NAMESPACE        	REVISION	UPDATED                                	STATUS  	CHART        	APP VERSION
ks-core	kubesphere-system	1       	2021-11-02 07:58:23.246064912 +0000 UTC	deployed	ks-core-0.1.0	v3.1.0
```

```shell
kubectl get deploy,rs -n kubesphere-system 
```

result

```
NAME                                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ks-apiserver            0/0     0            0           3h22m
deployment.apps/ks-console              0/0     0            0           3h22m
deployment.apps/ks-controller-manager   0/0     0            0           3h22m
deployment.apps/ks-installer            1/1     1            1           3h23m

NAME                                               DESIRED   CURRENT   READY   AGE
replicaset.apps/ks-apiserver-5bc68c6f5b            0         0         0       3h22m
replicaset.apps/ks-apiserver-5cf678767f            0         0         0       3h18m
replicaset.apps/ks-apiserver-68567ff74d            0         0         0       3h18m
replicaset.apps/ks-console-6c5dfffcf6              0         0         0       3h22m
replicaset.apps/ks-controller-manager-6f6ffc5d4    0         0         0       3h18m
replicaset.apps/ks-controller-manager-78d86666c    0         0         0       3h22m
replicaset.apps/ks-controller-manager-84f8bb47f5   0         0         0       3h18m
replicaset.apps/ks-installer-7fbc5d568f            1         1         1       3h23m
```

**Comment by pixiake** [comment]
please execute the following command to check:
```
kubectl describe rs -n kubesphere-system ks-console-6c5dfffcf6 
```

**Comment by watsy0007** [comment]
already deleted.
reinstalling with 3.1.1

**Comment by peter4431** [comment]
@pixiake 

```
╰─$ helm list -n kubesphere-system
NAME   	NAMESPACE        	REVISION	UPDATED                                	STATUS  	CHART        	APP VERSION
ks-core	kubesphere-system	1       	2021-11-02 16:14:44.925034448 +0800 CST	deployed	ks-core-0.1.0	v3.1.0
╭─peter@peterdemacbook ~/projs/basketball/pvpserverv2/pvp/deploy/kubernetes ‹ruby-2.6.3› ‹master*›
╰─$ kubectl get deploy,rs -n kubesphere-system
NAME                                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ks-apiserver            0/0     0            0           3h52m
deployment.apps/ks-console              0/0     0            0           3h52m
deployment.apps/ks-controller-manager   0/0     0            0           3h52m
deployment.apps/ks-installer            1/1     1            1           3h54m

NAME                                               DESIRED   CURRENT   READY   AGE
replicaset.apps/ks-apiserver-5d45f9fd87            0         0         0       3h52m
replicaset.apps/ks-apiserver-747789cfcd            0         0         0       3h49m
replicaset.apps/ks-apiserver-8597d7d456            0         0         0       3h50m
replicaset.apps/ks-console-577f68d787              0         0         0       3h52m
replicaset.apps/ks-controller-manager-65c668c486   0         0         0       3h49m
replicaset.apps/ks-controller-manager-79cfb44565   0         0         0       3h50m
replicaset.apps/ks-controller-manager-85d4496987   0         0         0       3h52m
replicaset.apps/ks-installer-5fd568f899            1         1         1       3h54m
╭─peter@peterdemacbook ~/projs/basketball/pvpserverv2/pvp/deploy/kubernetes ‹ruby-2.6.3› ‹master*›
╰─$ kubectl describe rs -n kubesphere-system ks-console-577f68d787
Name:           ks-console-577f68d787
Namespace:      kubesphere-system
Selector:       app=ks-console,pod-template-hash=577f68d787,tier=frontend
Labels:         app=ks-console
                pod-template-hash=577f68d787
                tier=frontend
Annotations:    deployment.kubernetes.io/desired-replicas: 0
                deployment.kubernetes.io/max-replicas: 0
                deployment.kubernetes.io/revision: 1
                meta.helm.sh/release-name: ks-core
                meta.helm.sh/release-namespace: kubesphere-system
Controlled By:  Deployment/ks-console
Replicas:       0 current / 0 desired
Pods Status:    0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=ks-console
                    pod-template-hash=577f68d787
                    tier=frontend
  Service Account:  kubesphere
  Containers:
   ks-console:
    Image:      kubesphere/ks-console:v3.2.0
    Port:       <none>
    Host Port:  <none>
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:        20m
      memory:     100Mi
    Liveness:     tcp-socket :8000 delay=15s timeout=15s period=10s #success=1 #failure=8
    Environment:  <none>
    Mounts:
      /etc/localtime from host-time (ro)
      /opt/kubesphere/console/server/local_config.yaml from ks-console-config (rw,path="local_config.yaml")
      /opt/kubesphere/console/server/sample from sample-bookinfo (rw)
  Volumes:
   ks-console-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      ks-console-config
    Optional:  false
   sample-bookinfo:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      sample-bookinfo
    Optional:  false
   host-time:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/localtime
    HostPathType:
Events:            <none>
```

**Comment by pixiake** [comment]
Why is the number of replicas 0 ?

Events has expired, please delete this rs (replicaset.apps/ks-console-577f68d787) and check the events of the newly generated rs.

**Comment by DevOpserzhao** [comment]
3.1 is successful

**Comment by pixiake** [comment]
Can you provide the information of `kubectl get node` ?

**Comment by DevOpserzhao** [comment]
> please execute the following command to check:
> 
> ```
> helm list -n kubesphere-system
> kubectl get deploy,rs -n kubesphere-system 
> ```

helm list -n kubesphere-system
kubectl get deploy,rs -n kubesphere-system 
NAME    NAMESPACE               REVISION        UPDATED                                 STATUS          CHART           APP VERSION
ks-core kubesphere-system       1               2021-11-03 07:52:22.00929077 +0000 UTC  deployed        ks-core-0.1.0   v3.1.0     

kubectl get deploy,rs -n kubesphere-system 
NAME                                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ks-apiserver            0/0     0            0           106m
deployment.apps/ks-console              0/0     0            0           106m
deployment.apps/ks-controller-manager   0/0     0            0           106m
deployment.apps/ks-installer            1/1     1            1           108m

NAME                                               DESIRED   CURRENT   READY   AGE
replicaset.apps/ks-apiserver-55c6d95b7f            0         0         0       103m
replicaset.apps/ks-apiserver-7bc5b5bfc8            0         0         0       103m
replicaset.apps/ks-apiserver-d7bf9687c             0         0         0       106m
replicaset.apps/ks-console-d5cbc9d4f               0         0         0       106m
replicaset.apps/ks-controller-manager-587bbd97f    0         0         0       106m
replicaset.apps/ks-controller-manager-6fb4f56d78   0         0         0       103m
replicaset.apps/ks-controller-manager-75c494d68f   0         0         0       103m
replicaset.apps/ks-installer-7fbc5d568f            1         1         1       108m

**Comment by DevOpserzhao** [comment]
> kubectl get node

kubectl get node
NAME                                                STATUS   ROLES    AGE    VERSION
ip-10-111-103-219.cn-northwest-1.compute.internal   Ready    <none>   114m   v1.20.10-eks-3bcdcd
ip-10-111-96-168.cn-northwest-1.compute.internal    Ready    <none>   114m   v1.20.10-eks-3bcdcd
ip-10-111-96-57.cn-northwest-1.compute.internal     Ready    <none>   114m   v1.20.10-eks-3bcdcd

**Comment by Falc0nreeper** [comment]
I have same issue installation not working on EKS eu-west-2
Internal error occurred: failed calling webhook \"validating-user.kubesphere.io\": Post \"https://ks-controller-manager.kubesphere-system.svc:443/validate-email-iam-kubesphere-io-v1alpha2-user?timeout=30s
