### ISSUE TITLE
offline-installation-tool.sh脚本写死了helm和cni插件版本

### ISSUE THREAD

**Issue by quqiangsheng** [kubesphere/ks-installer#1804]
当前使用他离线下载ks3.2.0和k8s1.21.5的离线文件时 下载下来的是旧版本的helm和cri ,kk安装时不会使用还会重新下载适合版本的helm和cri

**Comment by pixiake** [comment]
Support the use of environment variables to specify binary version.

https://github.com/kubesphere/ks-installer/pull/1805/files
