### ISSUE TITLE
use ks-installer install kubespherev3.1.1  create redis-ha-server-0 service  mkdir: can't create directory '/data/conf/': Permission denied

### ISSUE THREAD

**Issue by xiaokangshuai** [kubesphere/ks-installer#1870]
k8s version：v1.20.10
kubesphere ： v3.1.1
storageclass： cephfs   
 Based on the cephfs file storage, when the redis-ha-server-0 service is created and the redis data directory is created, the permission is denied; and the same kubernetes version and kubesphere version of ceph rbd will not report an error
`[root@master2 ~]# kubectl  logs -n kubesphere-system  redis-ha-server-0  config-init 
Could not connect to Redis at redis-ha:26379: Name does not resolve
mkdir: can't create directory '/data/conf/': Permission denied
`

![image](https://user-images.githubusercontent.com/21293110/147202428-ab2f12be-75be-4b43-a19e-31e9d5063cab.png)

**Comment by FeynmanZhou** [comment]
It looks like the storage server is not working correctly. Hi team @kubesphere/sig-installation @kubesphere/sig-storage , could you pls give any suggestion?

**Comment by xiaokangshuai** [comment]
the storage service can work normally, I have tested that creating a pod can be mounted normally

**Comment by pixiake** [comment]
Is  `PodSecurityPolicy` set in the cluster?

**Comment by xiaokangshuai** [comment]
> 是否在群集中设置？`PodSecurityPolicy`

no

**Comment by dkeven** [comment]
> the storage service can work normally, I have tested that creating a pod can be mounted normally

Do you mean the CephFS already works now?

**Comment by xiaokangshuai** [comment]
> 

yes, I have used cephfs as a persistent volume to deploy other applications in the k8s cluster

**Comment by stoneshi-yunify** [comment]
try to pause the init container (e.g. sleep 10000) then exec into it and check the current user (e.g. `id`) and if you can create the `/data/conf`.

the `/data` is mounted from a pvc so it's possible your cephfs(csi) created a volume with restricted permissions which doesn't allow the user in the init container to create a subdir.

**Comment by xiaokangshuai** [comment]
> 
The container is a normal user of redis and cannot create a directory
![image](https://user-images.githubusercontent.com/21293110/148037798-5d46f93c-ec72-4326-bb72-13470b7ec0bc.png)

**Comment by xiaokangshuai** [comment]
> > 
> 
> The container is a normal user of redis and cannot create a directory ![image](https://user-images.githubusercontent.com/21293110/148037798-5d46f93c-ec72-4326-bb72-13470b7ec0bc.png)

![image](https://user-images.githubusercontent.com/21293110/148038405-2bc233c6-4561-4252-b4c4-afabfa6024ca.png)

**Comment by stoneshi-yunify** [comment]
check if selinux is enabled. otherwise, add 
```
securityContext:
    fsGroup: 1000
```
to the redis spec may solve the problem temporarily.

**Comment by xiaokangshuai** [comment]
> 
So, has the permissions of the mount at this time become the user master and group of 1000? Then there is permission to create
Can this problem be fixed permanently

**Comment by stoneshi-yunify** [comment]
we don't have this issue on other storage systems. This issue is not caused by kubesphere, I guess any applications using pvc and started without root user will hit this problem in your environment. If you want permanent fix, try to tune your cephfs settings or ask this question in ceph community.

**Comment by xiaokangshuai** [comment]
> 我们在其他存储系统上没有此问题。此问题不是由 kubesphere 引起的，我猜任何使用 pvc 的应用程序和在没有 root 用户的情况下启动的应用程序都会在您的环境中遇到此问题。如果你想要永久修复，请尝试调整你的cephfs设置或在ceph社区中问这个问题。

ok，thanks
