### ISSUE TITLE
[v3.3/o11y/monitoring] Upgrade Prometheus stack

### ISSUE THREAD

**Issue by benjaminhuo** [kubesphere/ks-installer#1883]
**What's it about?**
Upgrade the Prometheus stack including:
- [x] Customize `kube-prometheus` v0.8+
- [x] Upgrade `node-exporter` from v0.18.1 to v1.x+
- [x] Upgrade `kube-state-metrics` from v1.9.x to 2.x+
- [x] Upgrade `prometheus-operator` to a latest version
- [ ] Adjust metrics in recording rules and ks-apiserver to be compatible with latest changes in kube-state-metrics & node exporter 

**What's the reason why we need it?**

Solve compatibility issues with K8s new versions and keep up with upstream features

**Area Suggestion**

/kind enhancement

/area monitoring

**Comment by zryfish** [comment]
Break change

/kind documentation

**Comment by junotx** [comment]
This upgrade will have to inherit some breaking changes of the upstream components, particularly the metrics changes. 

The built-in rules that use changed metrics in KubeSphere can be updated in ks-installer, while user-created rules that use them will have to be adjusted by themselves.

**Comment by benjaminhuo** [comment]
> This upgrade will have to inherit some breaking changes of the upstream components, particularly the metrics changes.
> 
> The built-in rules that use changed metrics in KubeSphere can be updated in ks-installer, while user-created rules that use them will have to be adjusted by themselves.

We can create a document to record which metrics have been renamed or changed
