### ISSUE TITLE
When KubeSphere be able to support arm arch

### ISSUE THREAD

**Issue by F10Sec** [kubesphere/ks-installer#1895]
arm架构虽然相较于x86架构应用还不够广泛，但是是否有kubesphere支持arm架构的计划呢？

**Comment by LinuxSuRen** [comment]
/retitle When KubeSphere be able to support arm arch

Most components of KubeSphere have the image of arm64. See also this document (written in Chinese) about [how to install KubeSphere in the arm64 arch](https://kubesphere.com.cn/forum/d/3113-arm64-k8s-kubesphere).

/close
