### ISSUE TITLE
/usr/src/kubesphere/conf/ks-config.yaml 在哪？

### ISSUE THREAD

**Issue by chinaboy007** [kubesphere/ks-installer#199]
按照指引https://github.com/kubesphere/ks-installer/blob/advanced-2.0.2/README_zh.md
到 第5步了
发现 deploy下没有 kubesphere.yaml ，只有kubesphere-installer.yaml
且 kubesphere-installer.yaml 中有 一行
command: ["ansible-playbook", "/usr/src/kubesphere/kubesphere.yaml", "-b", "-e", "@/usr/src/kubesphere/conf/ks-config.yaml"]

但是我找不到 /usr/src/kubesphere/kubesphere.yaml 和 /usr/src/kubesphere/conf/ks-config.yaml，job启动后一直是running状态，
使用kubectl get pod -n kubesphere-system 查看什么都没有

**Comment by FeynmanZhou** [comment]
@chinaboy007  是需要 apply 这个 deploy/kubesphere-installer.yaml 文件，之前的文档有一处需要更新，现在已经更新了，你重新参考文档安装试试。

**Comment by guoziqin** [comment]
都不行
