### ISSUE TITLE
试用kubesphere3.3.0-rc.3，未找到kubespheredev/ks-installer:v3.3.0-rc.3镜像文件

### ISSUE THREAD

**Issue by qa137** [kubesphere/ks-installer#2024]
**错误信息如下：**
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  5m42s                  default-scheduler  Successfully assigned kubesphere-system/ks-installer-765997d849-rfgml to master
  Normal   Pulling    4m7s (x4 over 5m41s)   kubelet            Pulling image "kubespheredev/ks-installer:v3.3.0-rc.3"
  Warning  Failed     4m3s (x4 over 5m37s)   kubelet            Failed to pull image "kubespheredev/ks-installer:v3.3.0-rc.3": rpc error: code = Unknown desc = Error response from daemon: manifest for kubespheredev/ks-installer:v3.3.0-rc.3 not found: manifest unknown: manifest unknown
  Warning  Failed     4m3s (x4 over 5m37s)   kubelet            Error: ErrImagePull
  Warning  Failed     3m48s (x6 over 5m37s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    39s (x19 over 5m37s)   kubelet            Back-off pulling image "kubespheredev/ks-installer:v3.3.0-rc.3"

应该是未上传镜像到docker

**Comment by qa137** [comment]
同时ks-console的yaml文件不存在kubespheredev/ks-console:nightly-20220621镜像，但docker上面kubespheredev/ks-console:v3.3.0-rc.3版本镜像存在。是否ks-installer的yaml配置存在问题

**Comment by codering** [comment]
+1
我感觉做事有点粗心大意。。。

**Comment by codering** [comment]
我看 “kubesphere/ks-installer:v3.3.0-rc.3” 却存在，我改用这个镜像来安装，结果 ks-apiserver， ks-console, ks-controller-manager 这些镜像有没有  v3.3.0-rc.3 版本。。。。

是不是原本应该发布 `kubespheredev/ks-installer:v3.3.0-rc.3` , 结果错发到 `kubesphere/ks-installer:v3.3.0-rc.3` ?

**Comment by qa137** [comment]
目前来看，应该是这个问题。
我已看到kubespheredev/ks-installer存在v3.3.0-rc.3的镜像了，这个配置是正确了。

我安装时，除遇到kubespheredev/ks-installer镜像不正确外。kubespheredev/ks-console:nightly-20220621镜像也不存在。目前来看就只有这两个问题，安装后即可正常使用。

ks-console的yaml文件Deployment的image是kubespheredev/ks-console:nightly-20220621镜像，这个镜像在docker中不存在。需要您修改ks-console的yaml的image镜像为v3.3.0-rc.3，或者发布kubespheredev/ks-console:nightly-20220621镜像即可解决。

**Comment by qa137** [comment]
<img width="631" alt="截屏2022-06-22 下午5 57 12" src="https://user-images.githubusercontent.com/3113623/175001457-4cf36dde-f9f7-4bf0-b2f7-c0b419ef3910.png">
不发布kubespheredev/ks-console:nightly-20220621镜像，crd配置时，需要不停的去改镜像

**Comment by codering** [comment]
我没用 nightly 镜像，现在有了 kubespheredev/ks-installer:v3.3.0-rc.3， 直接安装就可以了吧。

```sh
kubectl apply -f https://github.com/kubesphere/ks-installer/releases/download/v3.3.0-rc.3/kubesphere-installer.yaml
kubectl apply -f https://github.com/kubesphere/ks-installer/releases/download/v3.3.0-rc.3/cluster-configuration.yaml
```

**Comment by qa137** [comment]
之前因没有镜像，使用了替代镜像出现错误。现在已可以正常安装了。感谢！
