### ISSUE TITLE
monitoring endpoint 是否支持https,

### ISSUE THREAD

**Issue by gaochuang** [kubesphere/ks-installer#2240]
monitoring:
      # type: external   # Whether to specify the external prometheus stack, and need to modify the endpoint at the next line.
      endpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090 # Prometheus endpoint to get metrics data.

Q:
访问环境prometheus svc，仅支持https, 需要使用token或者TLS，部署时配置文件该如何配置? 如果支持是否有对应的example?

**Comment by frezes** [comment]
Currently not supported, there are two main problems:
1. The kubesphere monitoring stack mainly uses prometheus-operator, which does not support authentication configuration. see [Support basic_auth_users in web configuration for Prometheus and Alertmanager](https://github.com/prometheus-operator/prometheus-operator/issues/4200).
Therefore, the monitoring endpoint currently does not support https or authentication, although it is very simple to implement authentication configuration as client request code, and code contributions are welcome.

2. In fact, the configuration cost of accessing the external prometheus endpoint is very high, and the requirements are basically the same as all configurations of internal prometheus.

**Comment by gaochuang** [comment]
> Currently not supported, there are two main problems:
> 
> 1. The kubesphere monitoring stack mainly uses prometheus-operator, which does not support authentication configuration. see [Support basic_auth_users in web configuration for Prometheus and Alertmanager](https://github.com/prometheus-operator/prometheus-operator/issues/4200).
>    Therefore, the monitoring endpoint currently does not support https or authentication, although it is very simple to implement authentication configuration as client request code, and code contributions are welcome.
> 2. In fact, the configuration cost of accessing the external prometheus endpoint is very high, and the requirements are basically the same as all configurations of internal prometheus.

  Ok, Thanks for  your quicly reply.  In OpenShift Container Platform, Prometheus has been installed and we need to use prometheus that comes with the paltform. therefore,  https access is required。
