### ISSUE TITLE
request to http://ks-apiserver/oauth/token failed, reason: connect ECONNREFUSED 10.110.238.87:80

### ISSUE THREAD

**Issue by happy-Z** [kubesphere/ks-installer#2258]
![image](https://github.com/kubesphere/ks-installer/assets/58432632/66384246-afae-4466-b31c-f96364b13efa)

**Comment by happy-Z** [comment]
重启解决

**Comment by PedrinHm** [comment]
Reiniciar não resolveu aqui :(

**Comment by calvinyv** [comment]
> Reiniciar não resolveu aqui :(

then you need to provide more detail about your case ~
