### ISSUE TITLE
openpitrix_enable 置为 false 时，job运行出错

### ISSUE THREAD

**Issue by leoendless** [kubesphere/ks-installer#24]
TASK [ks-core/prepare : KubeSphere | Getting OP Secret] ************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "cat /etc/kubesphere/openpitrix/kubernetes/iam-config/secret-key.txt", "delta": "0:00:00.102802", "end": "2019-08-20 06:37:55.175247", "msg": "non-zero return code", "rc": 1, "start": "2019-08-20 06:37:55.072445", "stderr": "cat: /etc/kubesphere/openpitrix/kubernetes/iam-config/secret-key.txt: No such file or directory", "stderr_lines": ["cat: /etc/kubesphere/openpitrix/kubernetes/iam-config/secret-key.txt: No such file or directory"], "stdout": "", "stdout_lines": []}

**Comment by pixiake** [comment]
这个应该是自己build的镜像安装的吧？

原因： 
由于在做功能解耦事先添加了enable参数，内部还有依赖关系没有处理造成
