### ISSUE TITLE
allinone环境有的服务怎么有多个pod

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/ks-installer#279]
* [ ] 如图所示
![Screen Shot 2019-10-15 at 2 38 30 PM](https://user-images.githubusercontent.com/28859385/66806198-82607c80-ef59-11e9-8db8-93352f323eed.png)

**Comment by pixiake** [comment]
这个是对应组件的yaml中默认设置的   alerting-executor的副本数已重置为1
