### ISSUE TITLE
单master不需要多个console pod

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/ks-installer#301]
* [ ] 只要不是HA环境，即使是单master的多节点部署，console也应该一个pod就够了
![Screen Shot 2019-10-18 at 5 43 05 PM](https://user-images.githubusercontent.com/28859385/67084068-da53e900-f1ce-11e9-98ea-a16daf86c8fa.png)

**Comment by rayzhou2017** [comment]
logging是不是也不需要两个？两个是为了loggingHA还是分片 @huanggze ?
![Screen Shot 2019-10-18 at 5 58 30 PM](https://user-images.githubusercontent.com/28859385/67085144-dfb23300-f1d0-11e9-8e77-9dcfab496086.png)

**Comment by huanggze** [comment]
单节点的话，是为了分片。如果只给一个 es 数据节点的话，需要把 pvc 配大一点
