### ISSUE TITLE
不支持应用部署么

### ISSUE THREAD

**Issue by Linuxbody** [kubesphere/ks-installer#32]
这个版本安装完，没有这些菜单呢

![image](https://user-images.githubusercontent.com/9931457/63573915-26acef00-c5b9-11e9-822f-c21bf77903e9.png)

**Comment by rayzhou2017** [comment]
你需要从第一个示例开始创建企业空间，每个租户需要有自己的企业空间，然后在自己的企业空间里才能看到这些菜单。

**Comment by Linuxbody** [comment]
解决了
