### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by ChangMuChen** [kubesphere/ks-installer#326]
安装过程中，出现如下错误：
TASK [ks-devops/sonarqube : Sonarqube | Deploy Sonarqube] *********************************************************************************************************************************************************************************
Wednesday 23 October 2019  14:41:15 +0800 (0:00:00.275)       0:01:18.862 ***** 
fatal: [ks-allinone]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/helm upgrade --install ks-sonarqube /etc/kubesphere/sonarqube/sonarqube-0.13.5.tgz -f /etc/kubesphere/sonarqube/custom-values-sonarqube.yaml --namespace kubesphere-devops-system", "delta": "0:00:00.106132", "end": "2019-10-23 14:41:15.807242", "msg": "non-zero return code", "rc": 1, "start": "2019-10-23 14:41:15.701110", "stderr": "Error: UPGRADE FAILED: \"ks-sonarqube\" has no deployed releases", "stderr_lines": ["Error: UPGRADE FAILED: \"ks-sonarqube\" has no deployed releases"], "stdout": "", "stdout_lines": []}

PLAY RECAP ********************************************************************************************************************************************************************************************************************************
ks-allinone                : ok=181  changed=8    unreachable=0    failed=1   

Wednesday 23 October 2019  14:41:15 +0800 (0:00:00.216)       0:01:19.078 *****

**Comment by pixiake** [comment]
出现这种错误一般是有FAILED状态的release，可以`helm  list`查看，然后使用`helm del --purge {release name}`删掉失败的release
