### ISSUE TITLE
安装心得

### ISSUE THREAD

**Issue by ChangMuChen** [kubesphere/ks-installer#327]
很遗憾，我重复的安装了好几天，换了好几个环境，也没有安装成功。每当我解决了其中一个问题，总能遇到下一个问题。一直没有看到successful这个字样，总是看到failed。桑心...还在安装中...

**Comment by ChangMuChen** [comment]
当我关闭sonarqube 的安装时，接下来又报了这个错误
TASK [ks-devops/jenkins : ks-devops | Getting ks-sonarqube svc nodeport] ******************************************************************************************************************************************************************
Wednesday 23 October 2019  15:06:16 +0800 (0:00:00.302)       0:02:38.295 ***** 
fatal: [ks-allinone]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/kubectl get --namespace kubesphere-devops-system -o jsonpath='{.spec.ports[0].nodePort}' services ks-sonarqube-sonarqube", "delta": "0:00:00.139769", "end": "2019-10-23 15:06:16.474286", "msg": "non-zero return code", "rc": 1, "start": "2019-10-23 15:06:16.334517", "stderr": "Error from server (NotFound): services \"ks-sonarqube-sonarqube\" not found", "stderr_lines": ["Error from server (NotFound): services \"ks-sonarqube-sonarqube\" not found"], "stdout": "", "stdout_lines": []}

PLAY RECAP ********************************************************************************************************************************************************************************************************************************
ks-allinone                : ok=286  changed=106  unreachable=0    failed=1

**Comment by pixiake** [comment]
要关掉sonarqube的话需要在deploy中部署文件的config部分添加配置 `sonarqube_enable: False` ，不需要修改其他文件
https://github.com/kubesphere/ks-installer#configuration-table

**Comment by ChangMuChen** [comment]
> 要关掉sonarqube的话需要在deploy中部署文件的config部分添加配置 `sonarqube_enable: False` ，不需要修改其他文件
> https://github.com/kubesphere/ks-installer#configuration-table

nice,修改完，安装成功！
