### ISSUE TITLE
多节点安装，报错，ks-minio does not exist

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/ks-installer#340]
安装版本：2019-10-29
错误日志：

TASK [common : Kubesphere | Deploy minio] **************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/helm upgrade --install ks-minio /etc/kubesphere/minio-ha -f /etc/kubesphere/custom-values-minio.yaml --set fullnameOverride=minio --namespace kubesphere-system", "delta": "0:05:00.502818", "end": "2019-10-29 04:01:51.342975", "msg": "non-zero return code", "rc": 1, "start": "2019-10-29 03:56:50.840157", "stderr": "Error: timed out waiting for the condition", "stderr_lines": ["Error: timed out waiting for the condition"], "stdout": "Release \"ks-minio\" does not exist. Installing it now.", "stdout_lines": ["Release \"ks-minio\" does not exist. Installing it now."]}

**Comment by pixiake** [comment]
timed out waiting for the condition

可以按照下边链接配置机器防火墙规则：
https://github.com/kubesphere/ks-installer/blob/master/docs/NetWorkAccess.md

**Comment by shaowenchen** [comment]
解决问题。

/close

**Comment by zhangpfly** [comment]
@shaowenchen 你好，想问一下最后是怎么解决的？我现在也遇到同样的问题了。
检查了一下防火墙，已经把selinux和Firewall关掉了。

TASK [common : Kubesphere | Deploy minio] **************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/helm upgrade --install ks-minio /etc/kubesphere/minio-ha -f /etc/kubesphere/custom-values-minio.yaml --set fullnameOverride=minio --namespace kubesphere-system --wait --timeout 1800\n", "delta": "0:30:00.948378", "end": "2019-11-11 09:53:01.606320", "msg": "non-zero return code", "rc": 1, "start": "2019-11-11 09:23:00.657942", "stderr": "Error: release ks-minio failed: timed out waiting for the condition", "stderr_lines": ["Error: release ks-minio failed: timed out waiting for the condition"], "stdout": "Release \"ks-minio\" does not exist. Installing it now.", "stdout_lines": ["Release \"ks-minio\" does not exist. Installing it now."]}

**Comment by shaowenchen** [comment]
在防火墙添加，允许 IPENCAP / IPIP 协议
