### ISSUE TITLE
托管的 K8S 集群拿不到 etcd，是否可以部署 kubesphere？

### ISSUE THREAD

**Issue by pythonton** [kubesphere/ks-installer#35]
使用腾讯云的托管 K8S ，拿不到 etcd 的 IP，请问是否可以部署 kubesphere？

**Comment by pixiake** [comment]
可以部署 ，但是应该获取不到etcd监控，不过可以看下kube-apiserver的yaml文件，启动参数里一般会有etcd地址以及相关证书。
@benjaminhuo @huanggze

**Comment by pythonton** [comment]
好的，谢谢。
