### ISSUE TITLE
已经部署成功了为什么 gitlab 404

### ISSUE THREAD

**Issue by wangxu01** [kubesphere/ks-installer#363]
default backend - 404

# kubectl  get pod -n kubesphere-devops-system
NAME                                                       READY   STATUS      RESTARTS   AGE
ks-devops-db-ctrl-job-cwj9x                                0/1     Completed   3          30m
ks-devops-db-init-job-w5fdx                                0/1     Completed   0          30m
ks-gitlab-gitaly-0                                         1/1     Running     0          32m
ks-gitlab-gitlab-shell-6d8b4854d6-sxtz9                    1/1     Running     0          8m14s
ks-gitlab-gitlab-shell-6d8b4854d6-t59x2                    1/1     Running     0          32m
ks-gitlab-migrations.1-p9wxf                               0/1     Completed   0          32m
ks-gitlab-minio-767f58cb65-qj9nv                           1/1     Running     0          32m
ks-gitlab-nginx-ingress-controller-7fdbc89889-rsrkt        1/1     Running     0          32m
ks-gitlab-nginx-ingress-default-backend-67fcbdbdf4-5wwks   1/1     Running     0          32m
ks-gitlab-postgresql-77c44dbdb6-ws27m                      2/2     Running     0          32m
ks-gitlab-redis-59cdcfff57-7v8rs                           2/2     Running     0          32m
ks-gitlab-registry-754df9886c-ht64c                        1/1     Running     0          32m
ks-gitlab-sidekiq-all-in-1-84f7f46c4d-l2f4h                1/1     Running     0          6m10s
ks-gitlab-task-runner-68dc9d8468-zdddl                     1/1     Running     0          32m
ks-gitlab-unicorn-57b6ffbdf9-wtl4r                         2/2     Running     0          32m
ks-gitlab-unicorn-57b6ffbdf9-wxmm4                         2/2     Running     0          32m
ks-harbor-harbor-chartmuseum-6cfbf6d968-8rcqw              1/1     Running     0          33m
ks-harbor-harbor-clair-6668d9985-8c6b7                     1/1     Running     6          33m
ks-harbor-harbor-core-754f598947-bthhc                     1/1     Running     3          33m
ks-harbor-harbor-database-0                                1/1     Running     1          33m
ks-harbor-harbor-jobservice-5b7bb57489-2sz4z               1/1     Running     3          33m
ks-harbor-harbor-nginx-6dcbcf4cdf-g5k85                    1/1     Running     0          33m
ks-harbor-harbor-portal-54b6984795-q247t                   1/1     Running     0          33m
ks-harbor-harbor-redis-0                                   1/1     Running     0          33m
ks-harbor-harbor-registry-699556c6cc-4nhtt                 2/2     Running     0          33m
ks-harbor-setup-ldap-f22hq                                 0/1     Completed   0          16m
ks-jenkins-59f55c698b-p4wpx                                1/1     Running     0          14m
ks-sonarqube-postgresql-5c4db956d7-vp65f                   1/1     Running     0          30m
ks-sonarqube-sonarqube-58f8fbc89-v9g62                     1/1     Running     2          30m
s2ioperator-0                                              1/1     Running     1          30m
uc-jenkins-update-center-86f48694b4-fls6w                  1/1     Running     0          33m

**Comment by wangxu01** [comment]
域名访问就行了

**Comment by oliver-csu** [comment]
不行啊

**Comment by changorz** [comment]
还是不行？？？
