### ISSUE TITLE
已有的kubesphere中怎么设置istio网络的外网权限

### ISSUE THREAD

**Issue by BoBo-G** [kubesphere/ks-installer#37]
在kubesphere中部署的应用需要访问集群外部网络 而istio的egress会拦截到所有不是集群中的外部网络返回404 怎么在不影响现有集群的情况下设置istio的拦截规则

**Comment by zryfish** [comment]
请问访问不到的url是多少，可以参考 https://istio.io/docs/reference/config/networking/v1alpha3/service-entry/ 为需要访问的 Hosts 创建 serviceentry

**Comment by BoBo-G** [comment]
我修改了istio-inject-sider的cm 重新部署了所有的istio-egress
