### ISSUE TITLE
configmap配置没生效

### ISSUE THREAD

**Issue by kerven88** [kubesphere/ks-installer#4]
我修改了kubesphere.yaml配置文件的configmap设置不部署ks-logging相关的pod，但是没生效，还是启动了es和fluent相关的pod。
logging_enable: False
![123456](https://user-images.githubusercontent.com/51351006/63068938-a72f7800-bf47-11e9-9032-09a854f98188.png)

根据ansible-playbook里面的配置，true时候才会部署ks-logging相关服务。
 - { role: ks-logging, when: "logging_enable == true" }
![654321](https://user-images.githubusercontent.com/51351006/63068999-d9d97080-bf47-11e9-8068-1c1e2a974edf.png)

查看相关的ks-logging pod
$kubectl get  pods -n kubesphere-logging-system
![234234](https://user-images.githubusercontent.com/51351006/63069051-0db49600-bf48-11e9-8119-0a5345d1a255.png)

**Comment by pixiake** [comment]
没看到installer的job    应该是没有安装成功   成功的话installer的job会变成complete状态   可以新建一个job看下安装日志

**Comment by kerven88** [comment]
> 没看到installer的job 应该是没有安装成功 成功的话installer的job会变成complete状态 可以新建一个job看下安装日志

我reset后重新安装一次可以了，麻烦帮忙看下另外一个configmap配置没生效的问题。

**Comment by pixiake** [comment]
yaml中使用的镜像是advanced-2.0.2分支build的    仅支持metrics-server和istio不安装，其它的会默认安装，不装logging相关组件的话会影响使用，后续版本会进行功能解耦，那样的话就可以按需安装了

**Comment by kerven88** [comment]
> yaml中使用的镜像是advanced-2.0.2分支build的 仅支持metrics-server和istio不安装，其它的会默认安装，不装logging相关组件的话会影响使用，后续版本会进行功能解耦，那样的话就可以按需安装了

tks！ 期待新版本的解耦。
另外，再问个操作问题，我新建了一个role，user，以及企业空间，要怎样关联集群里面现有的namespaces权限呢？
