### ISSUE TITLE
error while evaluating conditional (plugins.storage == 'openebs-hostpath'): 'plugins' is undefined

### ISSUE THREAD

**Issue by huanggze** [kubesphere/ks-installer#440]
My environment is a clean-slate k8s (installed via kubeadm) + NFS storage as default sc

![image](https://user-images.githubusercontent.com/22350668/68536783-51763a80-0393-11ea-963b-50fb3dc65836.png)

**Comment by huanggze** [comment]
@pixiake @Forest-L

**Comment by pixiake** [comment]
要把存储填上   或者搞个default storage class

**Comment by huanggze** [comment]
搞了。而且文档里不是说 default storage class 是 Optional 吗。。 

![image](https://user-images.githubusercontent.com/22350668/68537034-75884a80-0398-11ea-8235-a41c7b2d9969.png)

**Comment by huanggze** [comment]
重新跑了一遍，下载了最新的 installer，暂时没有发现问题

**Comment by huanggze** [comment]
文档应该需要修改把 @FeynmanZhou
