### ISSUE TITLE
能在文档里说明是哪个svc访问吗？

### ISSUE THREAD

**Issue by JDalready** [kubesphere/ks-installer#45]
kubesphere-controls-system     default-http-backend                 ClusterIP   10.106.49.78     <none>        80/TCP                   66m
kubesphere-devops-system       controller-manager-metrics-service   ClusterIP   10.97.112.126    <none>        8443/TCP                 66m
kubesphere-devops-system       s2ioperator                          ClusterIP   10.100.63.204    <none>        443/TCP                  66m
kubesphere-devops-system       webhook-server-service               ClusterIP   10.102.71.7      <none>        443/TCP                  64m
kubesphere-monitoring-system   kube-state-metrics                   ClusterIP   None             <none>        8443/TCP,9443/TCP        65m
kubesphere-monitoring-system   node-exporter                        ClusterIP   None             <none>        9100/TCP                 65m
kubesphere-monitoring-system   prometheus-k8s                       ClusterIP   None             <none>        9090/TCP                 65m
kubesphere-monitoring-system   prometheus-k8s-system                ClusterIP   None             <none>        9090/TCP                 65m
kubesphere-monitoring-system   prometheus-operated                  ClusterIP   None             <none>        9090/TCP                 65m
kubesphere-monitoring-system   prometheus-operator                  ClusterIP   None             <none>        8080/TCP                 65m
kubesphere-system              ks-account                           ClusterIP   10.108.116.167   <none>        80/TCP                   66m
kubesphere-system              ks-apigateway                        ClusterIP   10.97.54.166     <none>        80/TCP                   66m
kubesphere-system              openldap                             ClusterIP   10.104.29.200    <none>        389/TCP                  66m
kubesphere-system              redis                                ClusterIP   10.108.107.71    <none>        6379/TCP                 66m
openpitrix-system              openpitrix-api-gateway               NodePort    10.105.177.150   <none>        9100:32054/TCP           66m
openpitrix-system              openpitrix-app-manager               ClusterIP   10.103.229.36    <none>        9102/TCP                 66m
openpitrix-system              openpitrix-category-manager          ClusterIP   10.100.48.4      <none>        9113/TCP                 66m
openpitrix-system              openpitrix-cluster-manager           ClusterIP   10.108.236.28    <none>        9104/TCP                 66m
openpitrix-system              openpitrix-db                        ClusterIP   10.106.119.233   <none>        3306/TCP                 66m
openpitrix-system              openpitrix-etcd                      ClusterIP   10.108.109.223   <none>        2379/TCP                 66m
openpitrix-system              openpitrix-iam-service               ClusterIP   10.98.189.159    <none>        9115/TCP                 66m
openpitrix-system              openpitrix-job-manager               ClusterIP   10.101.215.83    <none>        9106/TCP                 66m
openpitrix-system              openpitrix-minio                     ClusterIP   10.101.197.177   <none>        9000/TCP                 66m
openpitrix-system              openpitrix-repo-indexer              ClusterIP   10.99.109.56     <none>        9108/TCP                 66m
openpitrix-system              openpitrix-repo-manager              ClusterIP   10.110.30.231    <none>        9101/TCP                 66m
openpitrix-system              openpitrix-runtime-manager           ClusterIP   10.100.62.84     <none>        9103/TCP                 66m
openpitrix-system              openpitrix-task-manager              ClusterIP   10.102.198.80    <none>        9107/TCP                 66m

请问哪个svc是可以做暴露的

**Comment by pixiake** [comment]
访问console的话可以暴露kubesphere下的ks-console，默认是nodeport

**Comment by JDalready** [comment]
> 访问console的话可以暴露kubesphere下的ks-console，默认是nodeport

感谢你的回答  是我没部署成功
