### ISSUE TITLE
installer 新建 KS 时创建的存储类型应加上 access mode annotation

### ISSUE THREAD

**Issue by wnxn** [kubesphere/ks-installer#460]
完整的 annotations 示例。
```
storageclass.kubesphere.io/supported_access_modes: '["ReadWriteOnce","ReadOnlyMany","ReadWriteMany"]'
```

每种存储类型 accessmode 
qingcloud-csi, qingstor-csi, local: ReadWriteOnce
ceph rbd :"ReadWriteOnce","ReadOnlyMany"
nfs, glusterfs: "ReadWriteOnce","ReadOnlyMany","ReadWriteMany"

**Comment by justahole** [comment]
配置格式

metadata:
  name: neonsan
  annotations:
    storageclass.kubesphere.io/supported_access_modes: '["ReadWriteOnce"]'
