### ISSUE TITLE
http://192.168.120.19:5080/yum_repo/iso/repodata/repomd.xml: [Errno 14] curl#7 - "Failed connect to 192.168.120.19:5080; No route to host"

### ISSUE THREAD

**Issue by 331575886** [kubesphere/ks-installer#464]
centos 7.5 集群部署出问题，
环境:
一台:taskbox
三台:master
两台:node

register-local,配置在taskbox上

**Comment by pixiake** [comment]
192.168.120.19这个是tasksbox么？ 可以`docker ps`看下5080这个容器起来了没有，不过旧版本的离线部署用tasksbox的话可能会有些问题，需要手动处理

**Comment by 331575886** [comment]
19是task机器,docker ps   5000仓库是起来的,5080端口是没有起来的. 
version: kubeshere v2.0.2

**Comment by pixiake** [comment]
机器上有nginx:1.14-alpine的相关镜像吗？

**Comment by 331575886** [comment]
没有,我手动我手动起了个nginx,这个错通过了。
