### ISSUE TITLE
dockerhub.qingcloud.com Forbidden

### ISSUE THREAD

**Issue by guanbear** [kubesphere/ks-installer#477]
环境：某私有云内网环境，需要配置代理服务器访问网络。
从dockerhub.qingcloud.com 下载的image都会报错 forbidden，手动docker login一样报错

但是连官方的 docker hub 没有问题，也可以正常 docker login，不知道 dockerhub.qingcloud.com 有什么特殊的限制

docker login -u guest -p guest dockerhub.qingcloud.com
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://dockerhub.qingcloud.com/v2/: Get https://dockerauth.qingcloud.com:6000/auth?account=guest&client_id=docker&offline_token=true&service=dockerhub.qingcloud.com: Forbidden

**Comment by pixiake** [comment]
应该是6000被你们的防火墙限制了

**Comment by guanbear** [comment]
嗯有可能，该问题不具有普遍性，我先关了，谢谢
