### ISSUE TITLE
kubesphere/installRunner.py 报错

### ISSUE THREAD

**Issue by guanbear** [kubesphere/ks-installer#479]
安装的时候查看pod的日志：

命令 kubectl logs -n kubesphere-system $(kubectl get pod -n kubesphere-system -l app=ks-install -o jsonpath='{.items[0].metadata.name}') -f

发现installRunner.py 一直有如下报错，请问是什么原因呢？

Traceback (most recent call last):
  File "/hooks/kubesphere/installRunner.py", line 284, in <module>
    main()
  File "/hooks/kubesphere/installRunner.py", line 279, in main
    getResultInfo()
  File "/hooks/kubesphere/installRunner.py", line 84, in getResultInfo
    resultsList = checkExecuteResult()
  File "/hooks/kubesphere/installRunner.py", line 120, in checkExecuteResult
    taskProcessList = executeTask()
  File "/hooks/kubesphere/installRunner.py", line 154, in executeTask
    tasks = generateTaskLists()
  File "/hooks/kubesphere/installRunner.py", line 168, in generateTaskLists
    readyToEnabledList, readyToDisableList = getComponentLists()
  File "/hooks/kubesphere/installRunner.py", line 204, in getComponentLists
    for j, value in parameters.items():
AttributeError: 'str' object has no attribute 'items'
2019-11-13T08:52:55Z ERROR    : TASK_RUN TASK_HOOK_RUN 'kubesphere/installRunner.py' on 'KUBE_EVENTS' failed. Will retry after delay. Failed count is 76. Error: kubesphere/installRunner.py FAILED: exit status 1
2019-11-13T08:52:55Z INFO     : TASK_RUN Delay for 5s
2019-11-13T08:53:00Z INFO     : TASK_RUN HookRun@KUBE_EVENTS kubesphere/installRunner.py
2019-11-13T08:53:00Z INFO     : Running hook 'kubesphere/installRunner.py' binding 'KUBE_EVENTS' ...
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

**Comment by guanbear** [comment]
现在的问题是 kubesphere-system 的pod都可以running了，但是过段时间会被installer再次部署。然后kubesphere的其他namespace的pod都没有部署

**Comment by pixiake** [comment]
如何安装的呢？ 要先apply config文件哦~~

**Comment by guanbear** [comment]
以下pod会被重新部署：
NAMESPACE                    NAME                                                              READY   STATUS        RESTARTS   AGE
kubesphere-system            ks-account-866488664f-d9w9p                                       1/1     Terminating   0          4m15s
kubesphere-system            ks-account-866488664f-mrt4r                                       1/1     Terminating   0          4m15s
kubesphere-system            ks-account-866488664f-tdv45                                       1/1     Terminating   0          4m15s
kubesphere-system            ks-apiserver-864fc78c4d-5tgpm                                     1/1     Terminating   0          4m17s
kubesphere-system            ks-apiserver-864fc78c4d-cl2qs                                     1/1     Terminating   0          4m17s
kubesphere-system            ks-apiserver-864fc78c4d-kskhm                                     1/1     Terminating   0          4m17s
kubesphere-system            ks-controller-manager-6b47545b57-24vb7                            1/1     Terminating   0          4m12s
kubesphere-system            ks-controller-manager-6b47545b57-cgdxx                            1/1     Terminating   0          4m12s
kubesphere-system            ks-controller-manager-6b47545b57-dmnpk                            1/1     Terminating   0          4m12s

**Comment by pixiake** [comment]
如果在配置文件中开启了其它功能 ，会重启这些pod生效

**Comment by guanbear** [comment]
哦这样 ，但是现在就是没法安装成功了，感觉一直在陷入循环，我已经再准备删除，准备再尝试一次了。另外安装方式都是按照文档来的 config文件也apply了

**Comment by pixiake** [comment]
看上边的报错应该是配置文件里的格式有问题，可以贴下配置文件怎么修改的么？

**Comment by guanbear** [comment]
好的 ，这个是 config.yaml

---
apiVersion: v1
data:
  ks-config.yaml: |
    ---
    kube_apiserver_host: 127.0.0.1:6443
    persistence:
      storageClass: "openebs-cstor-disk-rep1"

    etcd:
      monitoring: True
      endpointIps: 10.224.44.223,10.224.44.224,10.224.44.225
      port: 2379
      tlsEnable: True

    common:
      mysqlVolumeSize: 20Gi
      minioVolumeSize: 20Gi
      etcdVolumeSize: 20Gi
      openldapVolumeSize: 2Gi
      redisVolumSize: 2Gi

    metrics-server:
      enabled: True

    console:
      enableMultiLogin: False  # enable/disable multi login
      port: 30880

    monitoring:
      prometheusReplicas: 1
      prometheusMemoryRequest: 400Mi
      prometheusVolumeSize: 20Gi
      grafana:
        enabled: True

    logging:
      enabled: True
      elasticsearchMasterReplicas: 1
      elasticsearchDataReplicas: 1
      logsidecarReplicas: 2
      elasticsearchVolumeSize: 20Gi
      logMaxAge: 7
      elkPrefix: logstash
      containersLogMountedPath: ""
      kibana:
        enabled: True

    openpitrix:
      enabled: True

    devops:
      enabled: False
      jenkinsMemoryLim: 2Gi
      jenkinsMemoryReq: 1500Mi
      jenkinsVolumeSize: 8Gi
      jenkinsJavaOpts_Xms: 512m
      jenkinsJavaOpts_Xmx: 512m
      jenkinsJavaOpts_MaxRAM: 2g
      sonarqube:
        enabled: False

    servicemesh:
      enabled: True

    notification:
      enabled: True

    alerting:
      enabled: True

    harbor:
      enabled: False
      domain: harbor.devops.kubesphere.local
    gitlab:
      enabled: False
      domain: devops.kubesphere.local

kind: ConfigMap
metadata:
  name: ks-installer
  namespace: kubesphere-system

**Comment by guanbear** [comment]
这个是 kubesphere-installer.yaml
这个就改了最下面的ks-installer image,我去掉了检查k8s 版本的roles 然后重新build了下，我的kubernetes版本是1.16 但是我通过设置 api runtime-config 把缺失的api加上了。
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubesphere-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ks-installer
  namespace: kubesphere-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ks-installer
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - tenant.kubesphere.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - certificates.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - devops.kubesphere.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - logging.kubesphere.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - jaegertracing.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - storage.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - '*'
  verbs:
  - '*'

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ks-installer
subjects:
- kind: ServiceAccount
  name: ks-installer
  namespace: kubesphere-system
roleRef:
  kind: ClusterRole
  name: ks-installer
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    app: ks-install
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ks-install
  template:
    metadata:
      labels:
        app: ks-install
    spec:
      serviceAccountName: ks-installer
      containers:
      - name: installer
        image: zcguan/ks-installer:2019111303
        imagePullPolicy: "Always"

**Comment by guanbear** [comment]
我再次部署 kubesphere-system 中的pod可以运行 ，但是installer还是在不停的再跑而且有installRunner.py的报错，其他namespace 都没有pod起来

[root@prod1 deploy]# kubectl  get pod -n kubesphere-system -o wide
NAME                                     READY   STATUS    RESTARTS   AGE     IP               NODE     NOMINATED NODE   READINESS GATES
etcd-779c89c557-jwn99                    1/1     Running   0          7m4s    10.233.94.71     prod25   <none>           <none>
ks-account-866488664f-7p5bv              1/1     Running   0          73s     10.233.106.183   prod2    <none>           <none>
ks-account-866488664f-942p8              1/1     Running   0          73s     10.233.94.73     prod25   <none>           <none>
ks-account-866488664f-zzw6c              1/1     Running   0          73s     10.233.95.173    prod1    <none>           <none>
ks-apigateway-5bb584ff8c-6vh28           1/1     Running   0          78s     10.233.95.181    prod1    <none>           <none>
ks-apigateway-5bb584ff8c-h54ds           1/1     Running   0          78s     10.233.93.167    prod3    <none>           <none>
ks-apigateway-5bb584ff8c-sptzw           1/1     Running   1          78s     10.233.106.181   prod2    <none>           <none>
ks-apiserver-864fc78c4d-d4jcp            1/1     Running   0          76s     10.233.80.151    prod8    <none>           <none>
ks-apiserver-864fc78c4d-npxp2            1/1     Running   0          76s     10.233.110.14    prod10   <none>           <none>
ks-apiserver-864fc78c4d-pwqqq            1/1     Running   0          76s     10.233.89.248    prod14   <none>           <none>
ks-console-87697d9d-4c2cn                1/1     Running   0          64s     10.233.95.179    prod1    <none>           <none>
ks-console-87697d9d-hrkgg                1/1     Running   0          64s     10.233.93.168    prod3    <none>           <none>
ks-console-87697d9d-vxzg2                1/1     Running   0          64s     10.233.106.180   prod2    <none>           <none>
ks-controller-manager-6b47545b57-8rcjl   1/1     Running   0          71s     10.233.95.176    prod1    <none>           <none>
ks-controller-manager-6b47545b57-mrkc2   1/1     Running   0          71s     10.233.94.74     prod25   <none>           <none>
ks-controller-manager-6b47545b57-tf6kc   1/1     Running   0          71s     10.233.89.249    prod14   <none>           <none>
ks-installer-856c4cc684-tddwp            1/1     Running   0          10m     10.233.80.149    prod8    <none>           <none>
minio-845b7bd867-jwdq2                   1/1     Running   0          7m57s   10.233.94.70     prod25   <none>           <none>
mysql-66df969d-6gbtm                     1/1     Running   0          7m6s    10.233.80.150    prod8    <none>           <none>
openldap-0                               1/1     Running   0          8m20s   10.233.95.166    prod1    <none>           <none>
openldap-1                               1/1     Running   0          7m23s   10.233.93.158    prod3    <none>           <none>
redis-ha-haproxy-ffb8d889d-24v7g         1/1     Running   1          8m35s   10.233.95.175    prod1    <none>           <none>
redis-ha-haproxy-ffb8d889d-82n2d         1/1     Running   4          8m35s   10.233.93.156    prod3    <none>           <none>
redis-ha-haproxy-ffb8d889d-fbz7h         1/1     Running   1          8m35s   10.233.106.179   prod2    <none>           <none>
redis-ha-server-0                        2/2     Running   0          8m35s   10.233.106.175   prod2    <none>           <none>
redis-ha-server-1                        2/2     Running   0          6m2s    10.233.93.171    prod3    <none>           <none>
redis-ha-server-2                        2/2     Running   0          5m40s   10.233.95.177    prod1    <none>           <none>

**Comment by guanbear** [comment]
我发现了一个问题 是不是我apiserver配的不对，不应该配 127.0.0.1 我每个node都起了个nginx 反向代理 apiserver，做ha，可以配置127.0.0.1吗

**Comment by guanbear** [comment]
我修改下 apiserver的配置再试下

**Comment by pixiake** [comment]
是把preinstall那个role删掉了么？

**Comment by guanbear** [comment]
没都删，只删了这部分：
- name: Stop if kuernetes version is nonsupport
  assert:
    that: kubernetes_version.stdout is version('v1.16.0', '<')
    msg: The current k8s version is not supported

**Comment by pixiake** [comment]
可以开个teamviewer（tv 12）或者向日葵，把信息发到 kubesphere@yunify.com看下

**Comment by guanbear** [comment]
好的 我改下apiserver配置再试下，再不行我发下远程信息，多谢多谢！

**Comment by guanbear** [comment]
原因找到了，apiserver那行不应该加，加了后格式和其他配置不一致导致解析错误。去掉就不报错了，怪我了，我close掉。
