### ISSUE TITLE
最简安装后如何启动 其他没有安装的组件

### ISSUE THREAD

**Issue by liangyuanpeng** [kubesphere/ks-installer#482]
![image](https://user-images.githubusercontent.com/28711504/68829146-d8ece200-06e2-11ea-9c08-abc151a1cb0d.png)

例如我想 启用 应用商店，支持在UI启动吗？或目前支持以任何方式启动吗

**Comment by pixiake** [comment]
https://github.com/kubesphere/ks-installer/blob/master/README_zh.md#%E5%AE%89%E8%A3%85%E5%8A%9F%E8%83%BD%E7%BB%84%E4%BB%B6
