### ISSUE TITLE
kubesphere部署成功后，应用商店未见任何应用

### ISSUE THREAD

**Issue by ethanxzw** [kubesphere/ks-installer#496]
kubesphere部署成功后，应用商店未见任何应用，手动添加本地应用仓库并同步后，应用商店中也未见应用。
![image](https://user-images.githubusercontent.com/41108414/69132684-800cb780-0aef-11ea-8d66-3b923cae3def.png)
![image](https://user-images.githubusercontent.com/41108414/69132730-99156880-0aef-11ea-9e6e-d59ba5fdb9bf.png)
![image](https://user-images.githubusercontent.com/41108414/69132773-aa5e7500-0aef-11ea-9c97-753694c42d0a.png)

**Comment by pengcong06** [comment]
可能是job执行不成功,重新泡一下
kubectl get job hyperpitrix-release-app-job -n openpitrix-system -o json | jq 'del(.spec.selector)' | jq 'del(.spec.template.metadata.labels)' | kubectl replace --force -f

**Comment by ethanxzw** [comment]
重跑一下job就好了。
`kubectl get job hyperpitrix-release-app-job -n openpitrix-system -o json | jq 'del(.spec.selector)' | jq 'del(.spec.template.metadata.labels)' | kubectl replace --force -f -
`
![image](https://user-images.githubusercontent.com/41108414/69202082-6b760100-0b7b-11ea-856d-b4d2467c1544.png)
