### ISSUE TITLE
devops安装后管理界面无操作的按钮

### ISSUE THREAD

**Issue by ftlynx** [kubesphere/ks-installer#509]
ks-install 的配置中enable了devops，并且全部安装成功了，但是在管理界面找到devops相关的操作地方呢。比如说创建之类的，是还有其它依赖组件需要安装吗 
   devops:
      enabled: true
      jenkinsMemoryLim: 2Gi
      jenkinsMemoryReq: 1500Mi
      jenkinsVolumeSize: 8Gi
      jenkinsJavaOpts_Xms: 512m
      jenkinsJavaOpts_Xmx: 512m
      jenkinsJavaOpts_MaxRAM: 2g
      sonarqube:
        enabled: true

**Comment by Forest-L** [comment]
1、请参考下这个文档，https://kubesphere.io/docs/v2.1/zh-CN/introduction/intro/
