### ISSUE TITLE
默认安装的Elasticsearch Curator 版本不兼容es7，需要升级到5.7及以上.

### ISSUE THREAD

**Issue by puluto** [kubesphere/ks-installer#517]
默认版本5.5系列只能支持到Elasticsearch 6.x
[curator5.5支持列表](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.5/version-compatibility.html)

5.7版本开始支持Elasticsearch 7.x
[curator5.7支持列表](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.7/version-compatibility.html)

可以升级一下默认版本，毕竟文档上说的支持外接es7.x

**Comment by huanggze** [comment]
感谢反馈
