### ISSUE TITLE
部署不支持helm v3

### ISSUE THREAD

**Issue by caiwenhao** [kubesphere/ks-installer#528]
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/helm list\n", "delta": "0:00:00.381256", "end": "2019-12-27 03:16:56.458315", "msg": "non-zero return code", "rc": 1, "start": "2019-12-27 03:16:56.077059", "stderr": "Error: could not find tiller", "stderr_lines": ["Error: could not find tiller"], "stdout": "", "stdout_lines": []}

**Comment by pixiake** [comment]
installer的pod中还是helm2的版本，且应用商店功能还不支持helm3，持续改进中，后续版本会支持的
