### ISSUE TITLE
登录成功后没有重定向至主页

### ISSUE THREAD

**Issue by weiliang-ms** [kubesphere/ks-installer#538]
![image](https://user-images.githubusercontent.com/18642754/71716258-0cc8c600-2e4f-11ea-99c9-af8c236853cd.png)

需要手动删除端口号的/login 才会进入系统主页

**Comment by weiliang-ms** [comment]
![image](https://user-images.githubusercontent.com/18642754/71716378-7fd23c80-2e4f-11ea-92a7-0d27c0f63809.png)

**Comment by shaowenchen** [comment]
正常登陆时，应该是这样：

![image](https://user-images.githubusercontent.com/43693241/71774607-208a3e80-2fad-11ea-8097-0c007f8a6af4.png)

建议：
1，换个浏览器试下。
2，查看登陆之后的第一个请求，是否带上了登陆信息。

/area console
/assign @leoendless

**Comment by leoendless** [comment]
相同用户的连续登录会进入上一次的页面

**Comment by weiliang-ms** [comment]
换了chrome，执行以下操作：
1、手动清除cookie
2、访问ip:30880后 重定向至/login

![image](https://user-images.githubusercontent.com/18642754/71789659-51c74500-3067-11ea-8b7e-1b84e6a1eaa6.png)
应该是登录成功了，但是不知道为什么又302到/login了

手动去掉/login访问，进入主页
![image](https://user-images.githubusercontent.com/18642754/71789723-bbdfea00-3067-11ea-984b-d7304b1ccfa3.png)

**Comment by weiliang-ms** [comment]
> 相同用户的连续登录会进入上一次访问的页面

客户端 手动清楚cookie再次登录也不可以吗？

**Comment by leoendless** [comment]
你这个问题挺奇怪的，按道理登录正常会 redirect 到 / 页面，如果出现 403 错误才会回到 login 页面，可以用 chrome 浏览器试下吗

**Comment by weiliang-ms** [comment]
> 你这个问题挺奇怪的，按道理登录正常会 redirect 到 / 页面，如果出现 403 错误才会回到 login 页面，可以用 chrome 浏览器试下吗

我用的深度系统自带的chrome会有影响吗？

**Comment by weiliang-ms** [comment]
![image](https://user-images.githubusercontent.com/18642754/71793123-66f7a000-3076-11ea-8211-ee717f9a6b8f.png)
换了windows的chrome还是不行。
每次重新登录的时候，服务端的session会覆盖掉吗？

**Comment by leoendless** [comment]
可以看下 ks-apigateway 的日志在登录后是什么 api 导致了 403
或者提供下远程方式发到我邮箱(leoliu@yunify.com)远程下看看吧

**Comment by weiliang-ms** [comment]
![image](https://user-images.githubusercontent.com/18642754/71808320-7d1e5400-30a8-11ea-93a5-e776be1c0eef.png)
这个是截取的登录日志

**Comment by wansir** [comment]
@weiliang-ms  节点之间的时间没有同步，存在误差

**Comment by weiliang-ms** [comment]
确实是这个问题，我这边做模板机的时候，配置时钟同步的函数好像没有执行。
感谢！
