### ISSUE TITLE
jaeger 版本需要更新到 1.14.0+ 来支持 ES 7

### ISSUE THREAD

**Issue by Leboudin** [kubesphere/ks-installer#539]
当前版本是 1.13.1, 无法创建索引. 详见 [jaeger issue #1474 Support Elasticsearch 7.x](https://github.com/jaegertracing/jaeger/issues/1474)

-----

自行升级版本后问题可以解决

**Comment by zackzhangkai** [comment]
We had upgraded Jaeger to 1.17 in 3.0. This is the same in 3.1.0.
