### ISSUE TITLE
all-in-one在线安装使用本地私服metrics-server这个pod起不来

### ISSUE THREAD

**Issue by PYIsOk** [kubesphere/ks-installer#541]
2.1版本 All-in-one安装metrics-server这个pod起不来，describe发现如下图所示
![错误](https://user-images.githubusercontent.com/37820823/71868128-d4bfcc80-3147-11ea-9b84-a648167b8f61.jpg)

请问一下在哪里修改能够将image的地址gcr.azk8s.cn/google_containers/metrics-server-amd64:v0.3.1修改为本地私服地址？

**Comment by pixiake** [comment]
` kubectl edit cm ks-installer -n kubesphere-system`    
添加参数  
`metrics_server_repo: xxx/metrics-server-amd64`

**Comment by PYIsOk** [comment]
> ` kubectl edit cm ks-installer -n kubesphere-system`
> 添加参数
> `metrics_server_repo: xxx/metrics-server-amd64`

还是没起作用
