### ISSUE TITLE
Centos 8 多节点安装报错

### ISSUE THREAD

**Issue by huanggze** [kubesphere/ks-installer#545]
部署 1 master 1 node 青云 Centos 8 主机，提示 node 节点找不到 /usr/bin/python

![image](https://user-images.githubusercontent.com/22350668/72215379-792d7e80-354d-11ea-9345-8fb24dc337d2.png)

 尝试在 node 节点手动安装与 master 同版本的 python 2.7.15 后再次安装仍报错

![image](https://user-images.githubusercontent.com/22350668/72215446-995d3d80-354d-11ea-9882-f2e305fe84ad.png)

![image](https://user-images.githubusercontent.com/22350668/72215450-a2e6a580-354d-11ea-99a6-9fbd94ef9938.png)

**Comment by pixiake** [comment]
暂不支持centos 8
