### ISSUE TITLE
请问kubesphere-system中的kubesphere-config是在哪里初始化的

### ISSUE THREAD

**Issue by Old-Camel** [kubesphere/ks-installer#561]
![image](https://user-images.githubusercontent.com/22683201/72674005-96fa6680-3aac-11ea-8f0f-7ca0dae28869.png)

**Comment by pixiake** [comment]
https://github.com/kubesphere/ks-installer/blob/master/roles/ks-core/prepare/templates/kubesphere-config.yaml.j2
