### ISSUE TITLE
在k8s集群上安装ks2.1.0，启动组件遇到的问题 

### ISSUE THREAD

**Issue by F-liuhui** [kubesphere/ks-installer#573]
原k8s集群没有.csr和.key格式的文件，只有.pem格式的文件，例如kube-ca.pem和kube-ca-key.pem文件,要启动devops组件，secret要如何创建？看到有人提过同样的问题，但一直没得到回复。遇到问题得不到解答不利于ks的推广，希望能得到回复。

**Comment by Forest-L** [comment]
证书可以参考下如下方式：
```
kubectl -n kubesphere-system create secret generic kubesphere-ca  \
--from-file=ca.crt=/etc/kubernetes/pki/kube-ca.pem  \
--from-file=ca.key=/etc/kubernetes/pki/kube-ca-key.pem
```

**Comment by F-liuhui** [comment]
> 证书可以参考下如下方式：
> 
> ```
> kubectl -n kubesphere-system create secret generic kubesphere-ca  \
> --from-file=ca.crt=/etc/kubernetes/pki/kube-ca.pem  \
> --from-file=ca.key=/etc/kubernetes/pki/kube-ca-key.pem
> `
