### ISSUE TITLE
安装完2.1.1的installer之后，版本号仍是2.1.0

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/ks-installer#580]
测试步骤：
1、安装2.1.1的installer；
2、安装结束后，查看关于中的版本号，发现仍是2.1.0，需要更新为2.1.1
![image](https://user-images.githubusercontent.com/7677050/73638034-936a0080-46a4-11ea-9f59-63c8f3f129fb.png)

**Comment by Forest-L** [comment]
Fixed at https://github.com/kubesphere/ks-installer/pull/578
