### ISSUE TITLE
etcd集群监控失败--endpointIps写成域名

### ISSUE THREAD

**Issue by pog2g** [kubesphere/ks-installer#597]
如果etcd endpointIps写成域名监控将获取不到etcd节点信息，写成ip正常

**Comment by FeynmanZhou** [comment]
@pog2g 也就是说 etcd 监控的问题，已经解决了是么

**Comment by pog2g** [comment]
对的，，就是要写成ip，不能写成域名。。就害怕有的集群写的是hosts中的域名。。我不知道这算不算bug

**Comment by pog2g** [comment]
> @pog2g 也就是说 etcd 监控的问题，已经解决了是么

对的，，就是要写成ip，不能写成域名。。就害怕有的集群写的是hosts中的域名。。我不知道这算不算bug

**Comment by pixiake** [comment]
写成域名的话，pod中也要做对应的域名解析，需要你的dns服务器中配置相关规则
