### ISSUE TITLE
devops一直失败不知道啥子原因

### ISSUE THREAD

**Issue by pog2g** [kubesphere/ks-installer#603]
devops一直失败不知道啥子原因，日志结果：
![image](https://user-images.githubusercontent.com/48884933/74142821-9af55080-4c34-11ea-8a81-0d3de79ce829.png)

**Comment by pixiake** [comment]
可通过helm list检查组件状态
可以先删除ks-jenkins，之后重启ks-installer
`helm del  --purge  ks-jenkins`
