### ISSUE TITLE
关闭某些组件，组件对应pod并没有关闭

### ISSUE THREAD

**Issue by pog2g** [kubesphere/ks-installer#605]
实现步骤：
1.部署打开某些组件
2.通过kubectl edit cm ks-installer -n kubesphere-system关闭某些组件
3.服务组件已经发下没有服务组件了。。但通过kubectl get pod --all-namespaces查看pod还在，，或者通过管理界面查看项目进入发现pod还运行

比如服务中查看确认没有日志相关的

![image](https://user-images.githubusercontent.com/48884933/74151123-6ab6ad80-4c46-11ea-8c1f-47a46ca882a3.png)

但是项目中确实还在
![image](https://user-images.githubusercontent.com/48884933/74150723-79509500-4c45-11ea-934b-5c0600f6b7a7.png)

**Comment by pixiake** [comment]
目前不支持卸载，可以手动删除这些对应的workload
