### ISSUE TITLE
单节点无法安装，提示没有默认存储

### ISSUE THREAD

**Issue by pog2g** [kubesphere/ks-installer#665]
1.看文档只要,这个配置不填写就会使用本地存储，，但实际在已经存在的k8s单节点中安装kubesphere根本没法安装，直接提示没有存储。即官网说的这个字段不填写就使用本地存储
```
persistence:
      storageClass: ""
```

**Comment by pixiake** [comment]
这个参数不填的话，使用默认存储类型：
https://github.com/kubesphere/ks-installer/blob/master/README_zh.md#%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E

**Comment by pog2g** [comment]
@pixiake 请教下能提供你们All-in-One单节点模式安装的本地存储生成yaml文件吗？？？？

**Comment by pixiake** [comment]
如果已经创建了存储的话  这里填storageclass  name就行

如果要用本地存储的话可以参考https://github.com/openebs/openebs

**Comment by pog2g** [comment]
好的，，谢谢

On Feb 26, 2020, at 10:24 PM, pixiake <notifications@github.com<mailto:notifications@github.com>> wrote:


如果已经创建了存储的话 这里填storageclass name就行

如果要用本地存储的话可以参考https://github.com/openebs/openebs
