### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by hawking-lab** [kubesphere/ks-installer#677]
查看Pod状态：
kube-system         tiller-deploy-6d97d6b85c-rbq4t                 1/1     Running            1          46m
kubesphere-system   ks-installer-7d9fb945c7-mf25g                  1/1     Running            1          41m
kubesphere-system   minio-845b7bd867-thf67                         0/1     CrashLoopBackOff   9          38m
kubesphere-system   minio-make-bucket-job-z5sz7                    1/1     Running            9          30m
kubesphere-system   openldap-0                                     1/1     Running            0          40m
kubesphere-system   redis-6fd6c6d6f9-hkrfm                         1/1     Running            0          40m
[root@maxbase-dev-node-178 ~]# 

查看
# kubectl logs -f  -n kubesphere-system minio-make-bucket-job-z5sz7
Connecting to Minio server: http://minio:9000
mc: <ERROR> Unable to initialize new config from the provided credentials. Server not initialized, please try again.
"Failed attempts: 1"
mc: <ERROR> Unable to initialize new config from the provided credentials. Server not initialized, please try again.
"Failed attempts: 2"
mc: <ERROR> Unable to initialize new config from the provided credentials. Server not initialized, please try again.
"Failed attempts: 3"
mc: <ERROR> Unable to initialize new config from the provided credentials. Server not initialized, please try again.
"Failed attempts: 4"
mc: <ERROR> Unable to initialize n

 ~]# kubectl describe pods -n kubesphere-system minio-845b7bd867-thf67
Name:         minio-845b7bd867-thf67
Namespace:    kubesphere-system
Priority:     0
Node:         maxbase-dev-node-182/10.57.200.182
Start Time:   Mon, 02 Mar 2020 16:52:26 +0800
Labels:       app=minio
              pod-template-hash=845b7bd867
              release=ks-minio
Annotations:  checksum/config: cadb75194921ca14ae01c91438d67a3cf5341519b3ae85527baf27d6a83ee494
              checksum/secrets: c0a2180ce5e11287a026c1180e8158171ea73ecd24193f5c715906c5187295e1
Status:       Running
IP:           10.233.69.2
IPs:
  IP:           10.233.69.2
Controlled By:  ReplicaSet/minio-845b7bd867
Containers:
  minio:
    Container ID:  docker://e336a06c4b131c046f869c9ad2b4942a919e64b38c6211f4e52fec08488daa25
    Image:         minio/minio:RELEASE.2019-08-07T01-59-21Z
    Image ID:      docker-pullable://minio/minio@sha256:cdc1ad6ee7b16b35a8c26c00e7bed0482f21bcd8ce841813fb91600f7d7f2faf
    Port:          9000/TCP
    Host Port:     0/TCP
    Command:
      /bin/sh
      -ce
      /usr/bin/docker-entrypoint.sh minio -C /root/.minio/ server /data
    State:          Running
      Started:      Mon, 02 Mar 2020 17:26:53 +0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Mon, 02 Mar 2020 17:25:04 +0800
      Finished:     Mon, 02 Mar 2020 17:26:53 +0800
    Ready:          True
    Restart Count:  11
    Requests:
      cpu:      250m
      memory:   256Mi
    Liveness:   http-get http://:service/minio/health/live delay=5s timeout=1s period=30s #success=1 #failure=3
    Readiness:  http-get http://:service/minio/health/ready delay=5s timeout=1s period=15s #success=1 #failure=3
    Environment:
      MINIO_ACCESS_KEY:  <set to the key 'accesskey' in secret 'minio'>  Optional: false
      MINIO_SECRET_KEY:  <set to the key 'secretkey' in secret 'minio'>  Optional: false
      MINIO_BROWSER:     on
    Mounts:
      /data from export (rw)
      /root/.minio/ from minio-config-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ks-minio-token-4w7ft (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  export:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  minio
    ReadOnly:   false
  minio-user:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  minio
    Optional:    false
  minio-config-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  ks-minio-token-4w7ft:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ks-minio-token-4w7ft
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                   From                           Message
  ----     ------            ----                  ----                           -------
  Warning  FailedScheduling  36m (x9 over 44m)     default-scheduler              pod has unbound immediate PersistentVolumeClaims (repeated 5 times)
  Normal   Scheduled         36m                   default-scheduler              Successfully assigned kubesphere-system/minio-845b7bd867-thf67 to maxbase-dev-node-182
  Normal   Killing           30m (x3 over 34m)     kubelet, maxbase-dev-node-182  Container minio failed liveness probe, will be restarted
  Normal   Created           30m (x4 over 36m)     kubelet, maxbase-dev-node-182  Created container minio
  Normal   Started           30m (x4 over 36m)     kubelet, maxbase-dev-node-182  Started container minio
  Normal   Pulled            10m (x10 over 36m)    kubelet, maxbase-dev-node-182  Container image "minio/minio:RELEASE.2019-08-07T01-59-21Z" already present on machine
  Warning  BackOff           6m12s (x51 over 22m)  kubelet, maxbase-dev-node-182  Back-off restarting failed container
  Warning  Unhealthy         49s (x35 over 35m)    kubelet, maxbase-dev-node-182  Liveness probe failed: HTTP probe failed with statuscode: 503
[root@maxbase-dev-node-178 ~]#

**Comment by Forest-L** [comment]
@hawking-lab 
1、检查下minio服务的pv是否创建成功。kubectl get pv -n kubesphere-system;
2、如果存在则重新部署下minio服务，先scale为0，然后再为1。
kubectl scale deployment -n kubesphere-system minio --replicas=0
