### ISSUE TITLE
K8S 环境安装报错

### ISSUE THREAD

**Issue by hawking-lab** [kubesphere/ks-installer#767]
1、 使用kuberspary 创建的双master k8s 集群、在线最小安装kubesphere 进报错
`TASK [common : Kubesphere | Deploy openldap] ***********************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/helm upgrade --install ks-openldap /etc/kubesphere/openldap-ha -f /etc/kubesphere/custom-values-openldap.yaml --set fullnameOverride=openldap --namespace kubesphere-system\n", "delta": "0:00:00.818510", "end": "2020-06-12 06:56:59.463920", "msg": "non-zero return code", "rc": 1, "start": "2020-06-12 06:56:58.645410", "stderr": "Error: render error in \"openldap-ha/templates/statefulset.yaml\": template: openldap-ha/templates/statefulset.yaml:25:9: executing \"openldap-ha/templates/statefulset.yaml\" at <(.Values.ldap.replication) and eq .Values.ldap.replication \"true\">: can't give argument to non-function .Values.ldap.replication", "stderr_lines": ["Error: render error in \"openldap-ha/templates/statefulset.yaml\": template: openldap-ha/templates/statefulset.yaml:25:9: executing \"openldap-ha/templates/statefulset.yaml\" at <(.Values.ldap.replication) and eq .Values.ldap.replication \"true\">: can't give argument to non-function .Values.ldap.replication"], "stdout": "Release \"ks-openldap\" does not exist. Installing it now.", "stdout_lines": ["Release \"ks-openldap\" does not exist. Installing it now."]}
`

**Comment by Forest-L** [comment]
1、If Chinese is used, please go to the forum to ask questions. [forum](https://kubesphere.com.cn/forum/)
2、Dual master is not supported at present, but 3MASTER installation is supported
