### ISSUE TITLE
在已有k3s 集群上部署ks-account 和  ks-apigateway运行不正常

### ISSUE THREAD

**Issue by BlueSky-YJS** [kubesphere/ks-installer#774]
1.    ks-account报错
        - kubesphere-system              ks-account-f7c6dd476-6vvz6                0/1     Init:0/2           0          4h2m    10.42.0.53  一直是Init状态
       - 查看ks-account  的docker报错信息
          `waiting for redis
nc: bad address 'redis.kubesphere-system.svc'
nc: bad address 'redis.kubesphere-system.svc'
waiting for redis
waiting for redis
nc: bad address 'redis.kubesphere-system.svc'
waiting for redis
nc: bad address 'redis.kubesphere-system.svc'
nc: bad address 'redis.kubesphere-system.svc'
waiting for redis
waiting for redis
nc: bad address 'redis.kubesphere-system.svc'`
2. ks-apigateway无法正常运行，container未创建成功
3. 查看ks-console的docker运行日志，报错信息如下
`    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
[ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN redis.kubesphere-system.svc:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
[ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN redis.kubesphere-system.svc:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
[ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN redis.kubesphere-system.svc:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
[ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN redis.kubesphere-system.svc:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
[ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN redis.kubesphere-system.svc:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
[ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN redis.kubesphere-system.svc:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
[ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN redis.kubesphere-system.svc:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
[ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN redis.kubesphere-system.svc:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
[ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN redis.kubesphere-system.svc:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)`

系统版本信息如下：
`[root@vm06centos admin]# /usr/local/bin/helm version        
Client: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
[root@vm06centos admin]# /usr/local/bin/kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2-k3s.1", GitCommit:"b8b17ba55f20e590df507fce333dfee13ab438c6", GitTreeState:"clean", BuildDate:"2019-10-16T05:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`

实在不知道是什么问题了？能不能帮助解决呢？

**Comment by Forest-L** [comment]
1、If Chinese is used, please go to the forum to ask questions. [forum](https://kubesphere.com.cn/forum/)
2、According to the above information, there is a problem with DNS service, which can be detected.

**Comment by BlueSky-YJS** [comment]
Now this problem has been solved. All components are completely uninstalled, and then installed according to the brand-new machine. At the same time, the existing cluster is not used, and after using the k8s cluster automatically deployed by install, everything is normal and can be used normally
