### ISSUE TITLE
English version please? 

### ISSUE THREAD

**Issue by Skarlso** [kubesphere/ks-installer#78]
Hi! I'm really interested in these docs. Is an English translation in progress?

Thanks!

**Comment by FeynmanZhou** [comment]
@Skarlso Yes, we'll provide English translation for these docs today, including installation guides and tutorials, will let you know when post it.

**Comment by Skarlso** [comment]
Frigging awesome. :) Thanks!

**Comment by FeynmanZhou** [comment]
@Skarlso English translation is done, suggest you to install on your Kubernetes cluster. Also, we have free and online trial environment, for someone who wanna quick testing and preview. If you have any other questions, you can join [Slack Channel](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTZkNTdkYWNiYTVkMTM5ZThhODY1MjAyZmVlYWEwZmQ3ODQ1NmM1MGVkNWEzZTRhNzk0MzM5MmY4NDc3ZWVhMjE) to communicate with us.

**Comment by Skarlso** [comment]
Yay! Fantastic. :) Thank you very much. I'll install it this weekend and have a look. ;) thank you for your effort!
