### ISSUE TITLE
kubesphere-system ks-apigateway，ks-account，redis，openldap启动失败

### ISSUE THREAD

**Issue by heppytt** [kubesphere/ks-installer#817]
kubesphere安装之后界面可以出现
![image](https://user-images.githubusercontent.com/17058423/85828760-af894e00-b7bb-11ea-8b2e-45abcc9965f1.png)
但是我查看kubesphere的pod发现有几个pod没有装好
![image](https://user-images.githubusercontent.com/17058423/85828868-e3647380-b7bb-11ea-93be-aac42bcc5e0a.png)
然后我查看ks-apigateway-78bcdc8ffc-qhbzr  发现redis连不上 我的redis一直pending 等待中然后我去看redis
![image](https://user-images.githubusercontent.com/17058423/85828989-258db500-b7bc-11ea-8ff5-e94992327659.png)
redis日志信息并没出现。估计没有运行。不知道是什么回事。
![image](https://user-images.githubusercontent.com/17058423/85829053-45bd7400-b7bc-11ea-9c10-367be7defc0d.png)
然后我查看redis的描述信息如下，说是绑定磁盘挂载超时了。
![image](https://user-images.githubusercontent.com/17058423/85829148-903ef080-b7bc-11ea-8657-23dcd8eaed42.png)
我看了一下我服务器的磁盘还有32g可以用

我的内存是64G，还有个数据盘500应该够用了。我用的一个maste和2个node做的k8s集群。
想让你们帮我看看是哪里的原因啊？谢谢了。

**Comment by pixiake** [comment]
https://github.com/kubesphere/kubesphere/issues/1841
