### ISSUE TITLE
ks-installer install kubsphere3.0 several problems

### ISSUE THREAD

**Issue by ktpktr0** [kubesphere/ks-installer#852]
docker version：19.03
k8s version：1.17.3
Network components：calico
kubesphere version：3.0

Question 1: The fluentbit-operator pod status is CrashLoopBackOff

logs：

2020-07-02T08:34:35.259Z        INFO    controller-runtime.metrics      metrics server is starting to listen    {"addr": ":8080"}
2020-07-02T08:34:35.260Z        INFO    setup   starting manager
2020-07-02T08:34:35.262Z        INFO    controller-runtime.manager      starting metrics server {"path": "/metrics"}
2020-07-02T08:34:36.697Z        INFO    controller-runtime.controller   Starting EventSource    {"controller": "fluentbitconfig", "source": "kind source: /, Kind="}
2020-07-02T08:34:36.697Z        INFO    controller-runtime.controller   Starting EventSource    {"controller": "fluentbit", "source": "kind source: /, Kind="}
2020-07-02T08:34:36.799Z        INFO    controller-runtime.controller   Starting EventSource    {"controller": "fluentbitconfig", "source": "kind source: /, Kind="}
2020-07-02T08:34:38.306Z        ERROR   controller-runtime.source       if kind is a CRD, it should be installed before calling Start   {"kind": "FluentBit.logging.kubesphere.io", "error": "no matches for kind \"FluentBit\" in version \"logging.kubesphere.io/v1alpha2\""}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/source/source.go:88
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:165
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:198
sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startLeaderElectionRunnables.func1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/manager/internal.go:477
2020-07-02T08:34:38.306Z        DEBUG   controller-runtime.manager      leader-election runnable finished       {"runnable type": "*controller.Controller"}
2020-07-02T08:34:38.306Z        ERROR   setup   problem running manager {"error": "no matches for kind \"FluentBit\" in version \"logging.kubesphere.io/v1alpha2\""}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
main.main
        /workspace/main.go:95
runtime.main
        /usr/local/go/src/runtime/proc.go:203

Question 2: Prometheus-k8s-system-0 pod status is CrashLoopBackOff

describe pod:

Events:
  Type     Reason            Age                    From                Message
  ----     ------            ----                   ----                -------
  Normal   Scheduled         <unknown>              default-scheduler   Successfully assigned kubesphere-monitoring-system/prometheus-k8s-system-0 to k8s-node2
  Warning  FailedScheduling  <unknown>              default-scheduler   error while running "VolumeBinding" filter plugin for pod "prometheus-k8s-system-0": pod has unbound immediate PersistentVolumeClaims
  Warning  FailedScheduling  <unknown>              default-scheduler   error while running "VolumeBinding" filter plugin for pod "prometheus-k8s-system-0": pod has unbound immediate PersistentVolumeClaims
  Normal   Pulled            29m                    kubelet, k8s-node2  Container image "jimmidyson/configmap-reload:v0.3.0" already present on machine
  Normal   Created           29m                    kubelet, k8s-node2  Created container prometheus-config-reloader
  Normal   Started           29m                    kubelet, k8s-node2  Started container prometheus-config-reloader
  Normal   Pulled            29m                    kubelet, k8s-node2  Container image "kubesphere/prometheus-config-reloader:v0.38.3" already present on machine
  Normal   Created           29m                    kubelet, k8s-node2  Created container rules-configmap-reloader
  Normal   Started           29m                    kubelet, k8s-node2  Started container rules-configmap-reloader
  Normal   Created           29m (x4 over 29m)      kubelet, k8s-node2  Created container prometheus
  Normal   Pulled            29m (x4 over 29m)      kubelet, k8s-node2  Container image "kubesphere/prometheus:v2.5.0" already present on machine
  Normal   Started           29m (x4 over 29m)      kubelet, k8s-node2  Started container prometheus
  Warning  BackOff           4m57s (x125 over 29m)  kubelet, k8s-node2  Back-off restarting failed container

logs：

level=info ts=2020-07-02T08:39:55.038300593Z caller=kubernetes.go:201 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-07-02T08:39:55.039082492Z caller=kubernetes.go:201 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=error ts=2020-07-02T08:39:55.044476164Z caller=manager.go:675 component="rule manager" msg="loading groups failed" err="group \"etcd\", rule 3, \"etcdHighNumberOfLeaderChanges\": could not parse expression: parse error at char 149: unexpected \"[\" in function call, expected \")\""
level=error ts=2020-07-02T08:39:55.04453053Z caller=main.go:651 msg="Failed to apply configuration" err="error loading rules, previous rule set restored"
level=info ts=2020-07-02T08:39:55.044556125Z caller=main.go:431 msg="Stopping scrape discovery manager..."
level=info ts=2020-07-02T08:39:55.044569185Z caller=main.go:445 msg="Stopping notify discovery manager..."
level=info ts=2020-07-02T08:39:55.044576395Z caller=main.go:467 msg="Stopping scrape manager..."
level=info ts=2020-07-02T08:39:55.044587664Z caller=main.go:441 msg="Notify discovery manager stopped"
level=info ts=2020-07-02T08:39:55.0446227Z caller=main.go:427 msg="Scrape discovery manager stopped"
level=error ts=2020-07-02T08:39:55.044671399Z caller=endpoints.go:130 component="discovery manager scrape" discovery=k8s role=endpoint msg="endpoints informer unable to sync cache"
level=error ts=2020-07-02T08:39:55.044715809Z caller=endpoints.go:130 component="discovery manager scrape" discovery=k8s role=endpoint msg="endpoints informer unable to sync cache"
level=error ts=2020-07-02T08:39:55.044730108Z caller=endpoints.go:130 component="discovery manager scrape" discovery=k8s role=endpoint msg="endpoints informer unable to sync cache"
level=info ts=2020-07-02T08:39:55.044802129Z caller=main.go:461 msg="Scrape manager stopped"
level=error ts=2020-07-02T08:39:55.044832242Z caller=endpoints.go:130 component="discovery manager scrape" discovery=k8s role=endpoint msg="endpoints informer unable to sync cache"
level=info ts=2020-07-02T08:39:55.044837569Z caller=manager.go:657 component="rule manager" msg="Stopping rule manager..."
level=info ts=2020-07-02T08:39:55.044851415Z caller=manager.go:663 component="rule manager" msg="Rule manager stopped"
level=info ts=2020-07-02T08:39:55.04504869Z caller=notifier.go:512 component=notifier msg="Stopping notification manager..."
level=info ts=2020-07-02T08:39:55.045076719Z caller=main.go:616 msg="Notifier manager stopped"
level=error ts=2020-07-02T08:39:55.045138416Z caller=main.go:625 err="error loading config from \"/etc/prometheus/config_out/prometheus.env.yaml\": one or more errors occurred while applying the new configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\")"

Question 3: The status of ks-apiserver pod is CrashLoopBackOff

logs：

W0702 08:42:55.794586       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
Error: dial tcp: lookup elasticsearch-logging-data.kubesphere-logging-system.svc.cluster.local on 10.96.0.10:53: no such host
Usage:
  ks-apiserver [flags]

Check that there are no elasticsearch related pods in the names of kubesphere logging system

[root@k8s-master1 ~]# kubectl get pods -n kubesphere-logging-system
NAME                                           READY   STATUS             RESTARTS   AGE
fluentbit-operator-7f7c5cd9ff-j9vcf            0/1     CrashLoopBackOff   32         143m
kube-auditing-operator-5ff856ddc-7879z         1/1     Running            0          144m
kube-auditing-webhook-deploy-f99bfc9bd-mspz6   1/1     Running            0          149m

**Comment by huanggze** [comment]
Please try the latest version of ks-installer

**Comment by ktpktr0** [comment]
ok ,i will try again
