### ISSUE TITLE
现有ks中安装kubesphere，发现英文文档有重复错误，请修改英文的第2步和第3步

### ISSUE THREAD

**Issue by xugirl** [kubesphere/ks-installer#91]
Create the Secret of CA certificate of your current Kubernetes cluster.
Note: Follow the certificate paths of ca.crt and ca.key of your current cluster to create this secret.

kubectl -n kubesphere-system create secret generic kubesphere-ca  \
--from-file=ca.crt=/etc/kubernetes/pki/ca.crt  \
--from-file=ca.key=/etc/kubernetes/pki/ca.key 
Create the Secret of certificate for ETCD in your Kubernetes cluster.
Note: Create with the actual ETCD certificate location of the cluster; If the ETCD does not have a configured certificate, an empty secret is created（The following command applies to the cluster created by Kubeadm）

Note: Create the secret according to the your actual path of ETCD for the k8s cluster;

If the ETCD has been configured with certificates, refer to the following step:
$ kubectl -n kubesphere-system create secret generic kubesphere-ca  \
--from-file=ca.crt=/etc/kubernetes/pki/ca.crt  \
--from-file=ca.key=/etc/kubernetes/pki/ca.key 
If the ETCD has been not configured with certificates.

**Comment by FeynmanZhou** [comment]
@xugirl Fixed, see #92 , thanks for your feedback.
