### ISSUE TITLE
kubesphere v2.0.2离线安装失败

### ISSUE THREAD

**Issue by Carriezhangyan** [kubesphere/ks-installer#94]
ASK [ks-devops/ks-devops : OpenPitrix | Waiting for openpitrix-db] **********************************************************************************************************************************************************************************************************
Wednesday 18 September 2019  11:36:20 +0800 (0:00:00.560)       0:06:57.894 *** 
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (15 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (14 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (13 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (12 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (11 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (10 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (9 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (8 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (7 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (6 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (5 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (4 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (3 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (2 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (1 retries left).
fatal: [master]: FAILED! => {"attempts": 15, "changed": true, "cmd": "/usr/local/bin/kubectl -n openpitrix-system get pod | grep openpitrix-db-deployment | awk '{print $3}'", "delta": "0:00:00.179634", "end": "2019-09-18 11:41:26.813177", "rc": 0, "start": "2019-09-18 11:41:26.633543", "stderr": "", "stderr_lines": [], "stdout": "Pending", "stdout_lines": ["Pending"]}

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************
master                     : ok=253  changed=93   unreachable=0    failed=1   
node1                      : ok=183  changed=31   unreachable=0    failed=0   
node2                      : ok=183  changed=31   unreachable=0    failed=0

**Comment by pixiake** [comment]
检查下存储

**Comment by Carriezhangyan** [comment]
8cpu，16G内存，120G硬盘，，三个搭建集群的服务器均是这样的配置

出现问题的时候，检查了一下内存和硬盘，均剩足够大的空间。

**Comment by Carriezhangyan** [comment]
进入脚本逐步检查发现，其实是因为执行命令“kubectl -n openpitrix-system get pod | grep openpitrix-db-deployment”时的状态一直处于pending。

```
scripts]# kubectl get pods -n openpitrix-system
NAME                                                      READY   STATUS     RESTARTS   AGE
openpitrix-api-gateway-deployment-5cf8bbb55-5wqr5         0/1     Init:0/2   1          15h
openpitrix-app-manager-deployment-b57755796-w7grm         0/1     Init:0/2   1          15h
openpitrix-category-manager-deployment-75cf9456c5-hjdlt   0/1     Init:0/2   1          15h
openpitrix-cluster-manager-deployment-7b78db5767-s54gb    0/1     Init:0/2   1          15h
**openpitrix-db-deployment-86744bc95b-7fkqq                 0/1     Pending    0          15h**
openpitrix-etcd-deployment-744f68dc5b-9sxzj               0/1     Pending    0          15h
openpitrix-iam-service-deployment-6c84b6f89b-5989l        0/1     Init:0/2   1          15h
openpitrix-job-manager-deployment-bc557f44d-7cqvv         0/1     Init:0/2   1          15h
openpitrix-minio-deployment-6896f4b7f7-mxdgv              0/1     Pending    0          15h
openpitrix-repo-indexer-deployment-798cb9654f-4plq5       0/1     Init:0/2   1          15h
openpitrix-repo-manager-deployment-78cf477658-8mdlp       0/1     Init:0/2   1          15h
openpitrix-runtime-manager-deployment-68b6dc5f86-kzfpb    0/1     Init:0/2   1          15h
openpitrix-task-manager-deployment-7bf9b4fd89-wvtlk       0/1     Init:0/2   1          15h
```

**Comment by pixiake** [comment]
不是机器的硬盘空间 ，安装的时候配置的什么存储，检查下，pod挂不上盘所以失败

**Comment by Carriezhangyan** [comment]
nfs存储

修改的conf/vars.yml文件：

```
 scripts]# grep -i nfs ../conf/vars.yml
# NFS-Client provisioner deployment
nfs_client_enable: true
nfs_client_is_default_class: true
# Hostname of the NFS server(ip or hostname)
nfs_server: 192.168.37.165
# Basepath of the mount point to be used
nfs_path: /opt/kubesphere

```

**Comment by Carriezhangyan** [comment]
nfs服务没有启动。。。
只修改了vars.yml文件中的nfs配置，没有手动启动nfs服务导致。
