### ISSUE TITLE
ks部署，ks-alerting部署失败。参考#33 未成功

### ISSUE THREAD

**Issue by zy84338719** [kubesphere/ks-installer#96]
系统版本
k8s版本
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

错误信息
TASK [ks-alerting : ks-alerting | Waiting for alerting-db-init] ****************
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (30 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (29 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (28 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (27 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (26 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (25 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (24 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (23 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (22 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (21 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (20 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (19 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (18 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (17 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (16 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (15 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (14 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (13 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (12 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (11 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (10 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (9 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (8 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (7 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (6 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (5 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (4 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (3 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (2 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (1 retries left).
fatal: [localhost]: FAILED! => {"attempts": 30, "changed": true, "cmd": "/usr/local/bin/kubectl -n kubesphere-alerting-system get pod | grep alerting-db-init | awk '{print $3}'", "delta": "0:00:00.112037", "end": "2019-09-18 15:25:44.449905", "rc": 0, "start": "2019-09-18 15:25:44.337868", "stderr": "", "stderr_lines": [], "stdout": "Init:0/1", "stdout_lines": ["Init:0/1"]}

PLAY RECAP *********************************************************************
localhost                  : ok=111  changed=100  unreachable=0    failed=1    skipped=34   rescued=0    ignored=1

```
kubectl -n kube-system edit configmap coredns 
```

apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream 
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf 《《这里已经与#33不同
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap

```
cat  /etc/resolv.conf 只有这个俩
nameserver 127.0.0.53
options edns0
```

**Comment by zy84338719** [comment]
```
➜  ~ kubectl get pod -n kubesphere-system
NAME                                     READY   STATUS     RESTARTS   AGE
ks-account-7696b8bc4f-4hvkr              0/1     Init:0/2   0          15m
ks-apigateway-5c56f79976-nbrpt           1/1     Running    0          15m
ks-console-75b6cb84c-2ng7r               1/1     Running    0          15m
ks-console-75b6cb84c-q7qf5               1/1     Running    0          15m
ks-controller-manager-785f69f56b-j4sq5   1/1     Running    0          15m
ks-docs-65bd89559b-9k2wk                 1/1     Running    0          99m
openldap-59966b99dd-wv9dn                1/1     Running    0          100m
redis-7c659f6f4f-jncw2                   1/1     Running    0          100m
```

**Comment by pixiake** [comment]
kubectl  get   pod  -n openpitrix-system  看下是不是也有很多pod是init状态
大概率是k8s环境的dns有问题

**Comment by zy84338719** [comment]
是的，可否提供一个完整的dns解决方案？
