### ISSUE TITLE
安装无法继续，卡住了

### ISSUE THREAD

**Issue by eeokee** [kubesphere/ks-installer#969]
k8s版本：1.18.5
ks版本：3.0

按照首页的安装顺序，下载并apply，仅修改了cluster-configuration.yaml的storageClass
storageClass: "gluster"

安装卡住了无法继续，请问要如何修复？

日志如下：
![image](https://user-images.githubusercontent.com/3079825/88996186-31bae400-d31f-11ea-9039-86004f454e12.png)

**Comment by rayzhou2017** [comment]
Please use English

**Comment by pixiake** [comment]
You can execute  `kubectl rollout restart deploy -n kubesphere-system ks-installer` to update image.

**Comment by eeokee** [comment]
@pixiake   重新重置k8s基础环境后，重新安装还是无法成功。

安装日志
![image](https://user-images.githubusercontent.com/3079825/89017329-b7a15400-d34c-11ea-8415-1294fe7c3a3d.png)

pod
![image](https://user-images.githubusercontent.com/3079825/89017373-cc7de780-d34c-11ea-99c7-42f46412f08e.png)

redis-ha-server-0 日志
![image](https://user-images.githubusercontent.com/3079825/89017928-a573e580-d34d-11ea-97d1-296d77ba5c17.png)

storageclass
![image](https://user-images.githubusercontent.com/3079825/89018204-0f8c8a80-d34e-11ea-9877-be79d4211b16.png)
